# NixOS module for theyOS.
# Usage: services.theyos.enable = true; services.theyos.user = "myuser"; ...
flakeSelf:

{ config, lib, pkgs, ... }:

let
  cfg = config.services.theyos;
  theyosPkgs = flakeSelf.packages.${pkgs.stdenv.hostPlatform.system};

  passwordFile = if cfg.adminPasswordFile != ""
    then cfg.adminPasswordFile
    else "${cfg.secretsDir}/admin-password";
  pepperFile = if cfg.sessionPepperFile != ""
    then cfg.sessionPepperFile
    else "${cfg.secretsDir}/session-pepper";

in
{
  # ── Imports ──────────────────────────────────────────────────────────────────
  # Sub-modules that own their own option tree under
  # `services.theyos.<name>`. Imported here (not from the flake) so they
  # see the same `config.services.theyos.*` resolution this file builds.

  imports = [
    ./modules/llm-proxy.nix
  ];

  # ── Options ──────────────────────────────────────────────────────────────────

  options.services.theyos = {
    enable = lib.mkEnableOption "theyOS platform";

    user = lib.mkOption {
      type = lib.types.str;
      description = "System user that runs theyOS services.";
    };

    repoDir = lib.mkOption {
      type = lib.types.str;
      description = "Path to the theyos repo clone (runtime path, NOT copied to store).";
    };

    domain = lib.mkOption {
      type = lib.types.str;
      default = "localhost";
      description = "Base domain for the admin panel.";
    };

    adminPort = lib.mkOption {
      type = lib.types.port;
      default = 8892;
      description = "Admin panel HTTP port.";
    };

    householdPort = lib.mkOption {
      type = lib.types.port;
      default = 8091;
      description = "Bootstrap / household identity listener port (FR-039). Must be reachable from LAN candidates joining a multi-machine casa.";
    };

    accessMode = lib.mkOption {
      type = lib.types.enum [ "local" "tailscale" "domain" ];
      default = "local";
      description = "Network access mode.";
    };

    ownerAuthV2Rollout = lib.mkOption {
      type = lib.types.enum [ "legacy" "reviewed-core-v2" ];
      default = "legacy";
      description = ''
        Owner-auth v2 rollout value rendered into
        THEYOS_OWNER_AUTH_V2_ROLLOUT. The default `legacy` keeps every
        owner-auth operation on LegacyOnly behavior. `reviewed-core-v2` is the
        explicit future flip value and must only be set after the reviewed
        flip decision/sign-offs.
      '';
    };

    # Secrets — all types.str (runtime paths), NEVER types.path.
    secretsDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/theyos/secrets";
      description = "Directory for auto-generated secrets.";
    };

    adminPasswordFile = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Path to file containing admin password. Empty = auto-generated.";
    };

    sessionPepperFile = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Path to file containing session pepper. Empty = auto-generated.";
    };

    # Optional integrations
    cloudflare = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = cfg.accessMode == "tailscale";
        description = ''
          Install cloudflared package + systemd unit. The unit stays dormant
          (ConditionPathExists on the token file) until the operator runs
          Settings → Cloudflare in the admin UI to wire it up. Defaults to
          true on tailscale-only hosts because they cannot serve public sites
          any other way; flip to false to opt out.
        '';
      };
      tokenFile = lib.mkOption {
        type = lib.types.str;
        default = "/var/lib/cloudflared/token";
        # NOT in cfg.secretsDir on purpose: that dir is chowned to soyeht
        # by the theyos-secrets activation script, but cloudflared runs as
        # cfg.user and would lose read access on every rebuild.
        description = "Path to the cloudflared connector token (written by the admin backend on Cloudflare setup, read by cfg.user).";
      };
      apiTokenFile = lib.mkOption {
        type = lib.types.str;
        default = "${cfg.secretsDir}/cloudflare-api-token";
        description = "Path to the Cloudflare API token (lives in secretsDir, owned by soyeht, used by the admin backend to create tunnels and CNAMEs on the operator's behalf).";
      };
      configFile = lib.mkOption {
        type = lib.types.str;
        default = "/var/lib/theyos/cloudflared/config.yml";
        description = "Path to cloudflared config.yml — auto-generated by the admin backend on every public-site change.";
      };
    };

    tailscale.enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable Tailscale VPN integration.";
    };

    dnsmasq = {
      enable = lib.mkOption { type = lib.types.bool; default = false; };
      interface = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "LAN interface for dnsmasq DNS forwarder.";
      };
    };

    caddy = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = cfg.accessMode == "domain";
        description = "Enable Caddy reverse proxy as a native NixOS service.";
      };
      environmentFile = lib.mkOption {
        type = lib.types.str;
        default = "${cfg.repoDir}/.caddy.env";
        description = "Path to environment file with CF_API_TOKEN for DNS-01 TLS.";
      };
    };

    # Package overrides
    package = lib.mkOption {
      type = lib.types.package;
      default = theyosPkgs.theyos-runtime;
      description = "theyOS runtime package (service binaries only; no local claw builders).";
    };

    frontendPackage = lib.mkOption {
      type = lib.types.package;
      default = theyosPkgs.theyos-frontend;
      description = "theyOS frontend package.";
    };

    firecrackerPackage = lib.mkOption {
      type = lib.types.package;
      default = theyosPkgs.firecracker;
      description = "Firecracker binary package.";
    };

    kernelPackage = lib.mkOption {
      type = lib.types.package;
      default = theyosPkgs.firecracker-kernel;
      description = "Firecracker guest kernel (vmlinux).";
    };
  };

  # ── Config ───────────────────────────────────────────────────────────────────

  config = lib.mkIf cfg.enable {

    # ── System ───────────────────────────────────────────────────────────────
    # All system-level settings use mkDefault so the user's existing
    # base-configuration.nix takes priority if it sets them explicitly.

    # Service account: runs soyeht-admin-host.service.
    # Separate from cfg.user (the human admin) so a compromise of the service
    # process does not grant the attacker the admin's shell, SSH keys, or
    # NOPASSWD: ALL sudo.
    #
    # Naming note: repo/product/module namespace = "theyos"; the system
    # service account is "soyeht" to mirror the existing
    # soyeht-admin-host.service and the soyeht CLI. This split is intentional.
    users.users.soyeht = {
      isSystemUser = true;
      group = "soyeht";
      extraGroups = [ "kvm" ];  # /dev/kvm is already 0666 via udev; defensive membership.
      description = "theyOS service account (runs soyeht-admin-host.service)";
      # Explicit nologin — do NOT rely on the isSystemUser default, this
      # must be declared because shell-login prevention matters for security.
      shell = "${pkgs.shadow}/bin/nologin";
      # No `home` set intentionally: the service runs with HOME=/home/${cfg.user}
      # (configured in the unit environment) because vmrunner resolves
      # ~/firecracker/ from $HOME. This is a known limitation — see the
      # user-split plan's "Known limitation aceita" section.
    };

    users.groups.soyeht = {};

    users.users.${cfg.user} = {
      isNormalUser = true;
      # `soyeht` membership lets cloudflared (running as cfg.user) read the
      # connector token written by the admin backend (running as soyeht) into
      # /var/lib/cloudflared/. Without this, the token file's group permissions
      # don't grant access and cloudflared startup fails with a misleading
      # "token-file not readable" error.
      extraGroups = lib.unique (
        [ "kvm" "wheel" ] ++ lib.optional cfg.cloudflare.enable "soyeht"
      );
    };

    # Passwordless sudo remains required for host-side runtime operations that
    # cross namespace / privilege boundaries (for example vmrunner's sudo+nsenter
    # ip_forward setup) and for the base rootfs bootstrap path. The
    # install-nixos script creates a temporary sudoers file for the initial
    # `nixos-rebuild switch`, but NixOS regenerates /etc on rebuild, so the
    # declarative rule below is the persistent source of truth.
    security.sudo.extraRules = [
      # Human admin (cfg.user): unchanged. Tightening this NOPASSWD: ALL is
      # explicit follow-up work, not in the soyeht user-split scope.
      {
        users = [ cfg.user ];
        commands = [{ command = "ALL"; options = [ "NOPASSWD" ]; }];
      }

      # Service account (soyeht): narrow rule, ONLY nsenter. The single
      # runtime sudo call is vmrunner-rs/src/network.rs:466 which runs
      # `sudo nsenter ...` to write net.ipv4.ip_forward=1 inside the
      # Firecracker VM's netns (the kernel silently ignores the same write
      # from inside a user namespace, which is why the call crosses the
      # userns boundary via sudo nsenter). This rule exists so the service
      # process, running as soyeht, can perform that one operation without
      # inheriting any other host privileges.
      #
      # Path match note: the call site in vmrunner-rs invokes
      # `Command::new("/run/wrappers/bin/sudo").args(["nsenter", ...])` —
      # i.e., `sudo nsenter` without an absolute path. sudo then does a
      # PATH lookup via secure_path and resolves `nsenter` to
      # `/run/current-system/sw/bin/nsenter` on NixOS. sudo compares that
      # resolved path LITERALLY to the rule — symlinks are NOT followed
      # during match, even though /run/current-system/sw/bin/nsenter is
      # ultimately a symlink to ${pkgs.util-linux}/bin/nsenter.
      #
      # Therefore the rule must reference the stable /run/current-system
      # path. Using ${pkgs.util-linux}/bin/nsenter would evaluate to a
      # hash-dependent /nix/store/... path and never match `sudo nsenter`
      # via PATH lookup. We keep the pkgs.util-linux variant as a second
      # entry only as a safety net for callers that pass the store path
      # explicitly (none today, but documenting the intent).
      #
      # Validation gate (Phase 2-step-A of the plan): after deploying this
      # rule, before switching User= to soyeht, confirm the match with:
      #   sudo -u soyeht sudo -l -n
      #   sudo -u soyeht sudo -n nsenter -t 1 -n /bin/sh -c 'echo test'
      # If the match fails, the cutover WILL break the runtime.
      {
        users = [ "soyeht" ];
        commands = [
          { command = "/run/current-system/sw/bin/nsenter"; options = [ "NOPASSWD" ]; }
          { command = "${pkgs.util-linux}/bin/nsenter"; options = [ "NOPASSWD" ]; }
        ] ++ lib.optionals cfg.cloudflare.enable [
          # Allow the admin backend (running as soyeht) to manage cloudflared
          # so the operator can drive setup/teardown from the admin UI without
          # ever SSHing or editing nix. Path is the literal stable symlink
          # because sudo compares Cmnd entries without following links — see the
          # nsenter rule above for the same constraint.
          { command = "/run/current-system/sw/bin/systemctl reload cloudflared";  options = [ "NOPASSWD" ]; }
          { command = "/run/current-system/sw/bin/systemctl start cloudflared";   options = [ "NOPASSWD" ]; }
          { command = "/run/current-system/sw/bin/systemctl stop cloudflared";    options = [ "NOPASSWD" ]; }
          { command = "/run/current-system/sw/bin/systemctl restart cloudflared"; options = [ "NOPASSWD" ]; }
        ];
      }
    ];

    # Load both KVM modules — the kernel activates only the matching one.
    # Listing both avoids hardcoding Intel vs AMD at Nix evaluation time.
    boot.kernelModules = [ "kvm-intel" "kvm-amd" "tun" ];

    # /dev/kvm must be world-accessible: Firecracker runs inside unshare(2)
    # user namespaces which drop supplementary groups (kvm group is lost).
    services.udev.extraRules = ''
      KERNEL=="kvm", GROUP="kvm", MODE="0666"
    '';
    boot.kernel.sysctl."net.ipv4.ip_unprivileged_port_start" = lib.mkDefault 80;

    # Dev nodes for Firecracker guests + Caddy conf.d import directory.
    systemd.tmpfiles.rules = [
      "L+ /dev/ptmx - - - - /dev/pts/ptmx"
      "c /dev/full 0666 root root - 1:7"
      "c /dev/zero 0666 root root - 1:5"
      "c /dev/random 0666 root root - 1:8"
      "c /dev/urandom 0666 root root - 1:9"
      "c /dev/tty 0666 root root - 5:0"
      "L+ /dev/fd - - - - /proc/self/fd"
      "L+ /dev/stdin - - - - /proc/self/fd/0"
      "L+ /dev/stdout - - - - /proc/self/fd/1"
      "L+ /dev/stderr - - - - /proc/self/fd/2"
      # Firecracker runtime dirs owned by soyeht.
      # 'd' creates if missing; 'z' corrects ownership on already-existing dirs.
      # Non-recursive: assets/ contains Nix store symlinks that must not be
      # chown'd (see activation script comment for rationale).
      # assets/*, instances/*, bin/ live under THEYOS_HOME (~/firecracker/).
      # golden-build lives under THEYOS_DIR (repo root) — different base path.
      "d /home/${cfg.user}/firecracker 0755 soyeht soyeht -"
      "z /home/${cfg.user}/firecracker 0755 soyeht soyeht -"
      "d /home/${cfg.user}/firecracker/instances 0755 soyeht soyeht -"
      "z /home/${cfg.user}/firecracker/instances 0755 soyeht soyeht -"
      "d /home/${cfg.user}/firecracker/assets 0755 soyeht soyeht -"
      "z /home/${cfg.user}/firecracker/assets 0755 soyeht soyeht -"
      "d /home/${cfg.user}/firecracker/assets/goldens 0755 soyeht soyeht -"
      "z /home/${cfg.user}/firecracker/assets/goldens 0755 soyeht soyeht -"
      "d /home/${cfg.user}/firecracker/assets/snapshots 0755 soyeht soyeht -"
      "z /home/${cfg.user}/firecracker/assets/snapshots 0755 soyeht soyeht -"
      "d /home/${cfg.user}/firecracker/bin 0755 soyeht soyeht -"
      "z /home/${cfg.user}/firecracker/bin 0755 soyeht soyeht -"
      "d ${cfg.repoDir}/firecracker/golden-build 0755 soyeht soyeht -"
      "z ${cfg.repoDir}/firecracker/golden-build 0755 soyeht soyeht -"
    ] ++ lib.optionals cfg.caddy.enable [
      # Caddy needs to traverse the home dir to follow the conf.d symlink.
      "d /home/${cfg.user} 0711 ${cfg.user} users -"
      "d /etc/caddy/conf.d 0755 caddy caddy -"
      "L+ /etc/caddy/conf.d/caddy.caddy - - - - ${cfg.repoDir}/tailscale/caddy.caddy"
    ];

    # THEYOS_DIR must be set system-wide so the `soyeht` CLI can find the
    # repo from any directory. Without this, soyeht falls back to `pwd`
    # because the Nix store binary path cannot be walked up to find the repo.
    environment.variables.THEYOS_DIR = cfg.repoDir;

    # Trust the theyOS git repo for any process reading it via libgit2 (nix
    # flakes, git CLI) — defense-in-depth against the CVE-2022-24765
    # "dubious ownership" guard. Without this, code paths that read the
    # flake as root from a user-owned repo (nested sudo, manual `sudo nix
    # build`) fail with "repository path '…' is not owned by current user"
    # because libgit2 falls back to comparing the effective UID (0) against
    # the repo owner (cfg.user's UID).
    #
    # The primary fix lives in admin/rust/soyeht-rs/src/nixos.rs
    # (`nixos_update` no longer nests sudo, and downgrades git ops to the
    # repo owner via `runuser`). This block is a belt-and-suspenders
    # guardrail for other tools that might still trip the check.
    #
    # Narrow by design: only ${cfg.repoDir} is trusted, not `*`.
    #
    # TRADEOFF: `environment.etc."gitconfig".text` is NOT attrset-mergeable.
    # If another NixOS module also sets `environment.etc."gitconfig"`,
    # nixos-rebuild will fail with a duplicate-entry error at eval time.
    # If that ever happens, migrate to
    # `programs.git.config.safe.directory = [ cfg.repoDir ];` (which IS
    # mergeable, but requires `programs.git.enable = true`).
    environment.etc."gitconfig".text = ''
      [safe]
      	directory = ${cfg.repoDir}
    '';
    # When a host/test provides an external `pkgs` instance, nixpkgs rejects
    # module-level `nixpkgs.config` settings and expects them to be baked into
    # that instance instead. Keep the normal host behavior here, but let tests
    # that instantiate `pkgs` externally supply the same allowUnfreePredicate
    # at import time.
    nixpkgs.config = lib.mkIf (config.nixpkgs.pkgs == null) {
      allowUnfreePredicate = pkg:
        builtins.elem (lib.getName pkg) [ "claude-code" ];
    };

    # soyeht + all workspace binaries on PATH, plus runtime deps.
    environment.systemPackages = [
      cfg.package
      pkgs.claude-code
      pkgs.codex
      pkgs.opencode
      pkgs.slirp4netns
      pkgs.e2fsprogs
      pkgs.iproute2
      pkgs.iptables
      pkgs.curl
      pkgs.openssh
      pkgs.git
      pkgs.sqlite
      pkgs.lsof
    ];

    # Firewall.
    #
    # UDP 5353 is open for mDNS/Bonjour multicast (FR-017) — the household
    # engine publishes `_soyeht-household._tcp.local.` and
    # `_soyeht-setup._tcp.local.` records that iPhone/Mac discover via
    # NWBrowser. Without 5353 open, queries from peers on the same LAN are
    # silently dropped by the default NixOS firewall and discovery fails
    # (confirmed via `tcpdump -i any udp port 5353` showing 0 incoming
    # packets on devs 2026-05-20).
    networking.firewall = {
      enable = lib.mkDefault true;
      allowedTCPPorts = [ 80 443 22 cfg.adminPort cfg.householdPort ];
      allowedUDPPorts = [ 5353 ]
        ++ lib.optional cfg.tailscale.enable config.services.tailscale.port;
      trustedInterfaces = lib.optional cfg.tailscale.enable "tailscale0";
    };

    # SSH daemon — every theyOS install needs remote access (admin panel
    # deploy flow, `sudo soyeht update`, debugging). `mkDefault` lets the
    # operator still disable it explicitly in base-configuration.nix if
    # they're running fully headless.
    services.openssh.enable = lib.mkDefault true;

    # Nix flakes system-wide. `nixos-rebuild-ng` (the Python rewrite) enables
    # flakes internally, so `sudo soyeht update` works without this. But bare
    # `nix build`, `nix flake`, and any third-party script that invokes plain
    # `nix` will fail unless the feature is declared in the rebuilt nix.conf.
    # Declaring it here makes flakes durable across rebuilds without relying
    # on install-nixos's one-shot append to /etc/nix/nix.conf.
    nix.settings.experimental-features = lib.mkDefault [ "nix-command" "flakes" ];

    # Tailscale (conditional).
    services.tailscale.enable = lib.mkDefault cfg.tailscale.enable;

    # ── Caddy reverse proxy (native NixOS service) ──────────────────────────

    services.caddy = lib.mkIf cfg.caddy.enable {
      enable = true;
      package =
        if cfg.cloudflare.enable
        then pkgs.caddy.withPlugins {
          plugins = [ "github.com/caddy-dns/cloudflare@v0.2.4" ];
          hash = "sha256-pRrLBlYRaAyMYwPXeTy4WqWNRu/L9K6Mn2src11dGh8=";
        }
        else pkgs.caddy;
      configFile = "${cfg.repoDir}/distro/caddy/Caddyfile";
    };

    # Caddy needs to read the Caddyfile from the repo and Tailscale certs
    # from ~/theyos/tailscale/certs/. ProtectHome must be disabled because
    # the conf.d symlink points into the home directory.
    systemd.services.caddy = lib.mkIf cfg.caddy.enable {
      serviceConfig = {
        ProtectHome = lib.mkForce false;
        EnvironmentFile = cfg.caddy.environmentFile;
      };
    };

    users.users.caddy = lib.mkIf cfg.caddy.enable {
      extraGroups = [ "users" ];
    };

    # ── Activation scripts (LOCAL + DETERMINISTIC only) ──────────────────────

    system.activationScripts = {
      # 1. Generate secrets on first run (local, /dev/urandom).
      theyos-secrets = lib.stringAfter [ "users" ] ''
        mkdir -p ${cfg.secretsDir}
        if [ ! -f "${passwordFile}" ]; then
          ${pkgs.openssl}/bin/openssl rand -base64 16 > "${passwordFile}"
          chmod 600 "${passwordFile}"
          echo "[theyos] Generated admin password in ${passwordFile}"
        fi
        if [ ! -f "${pepperFile}" ]; then
          ${pkgs.openssl}/bin/openssl rand -hex 32 > "${pepperFile}"
          chmod 600 "${pepperFile}"
          echo "[theyos] Generated session pepper in ${pepperFile}"
        fi
        if [ ! -f "${cfg.secretsDir}/bootstrap-token" ]; then
          ${pkgs.openssl}/bin/openssl rand -base64 32 > "${cfg.secretsDir}/bootstrap-token"
          chmod 600 "${cfg.secretsDir}/bootstrap-token"
          echo "[theyos] Generated bootstrap token in ${cfg.secretsDir}/bootstrap-token"
        fi
        # Secrets are owned by the soyeht service account, not the admin.
        # The admin can still `sudo cat` if they need to inspect.
        chown soyeht:soyeht ${cfg.secretsDir} ${cfg.secretsDir}/* 2>/dev/null || true
      '';

      # 1b. Bootstrap .caddy.env on first run.
      #
      # services.caddy refuses to start when EnvironmentFile is missing, and
      # the file is gitignored (it can hold CF_API_TOKEN). Generate a minimal
      # template so the unit boots cleanly; the operator fills in CF_API_TOKEN
      # when they're ready to enable Cloudflare DNS-01 issuance.
      #
      # We never overwrite an existing file — operators who set their own
      # values (e.g. extra THEYOS_* vars) keep them across rebuilds.
      # 1c. Bootstrap empty cloudflared config + dir on first run.
      #
      # cloudflared.service refuses to start if --config points at a non-existent
      # file. The admin backend will overwrite this file every time a public
      # site is added/removed; this just ensures the file exists before that
      # happens (e.g. fresh install with cloudflare.enable=true and zero sites
      # yet). Owned by soyeht so the admin backend can rewrite it; mode 644
      # so cloudflared (running as cfg.user) can read it.
      theyos-cloudflared-bootstrap = lib.mkIf cfg.cloudflare.enable (lib.stringAfter [ "users" ] ''
        install -d -m 755 -o soyeht -g soyeht "$(dirname "${cfg.cloudflare.configFile}")"
        if [ ! -f "${cfg.cloudflare.configFile}" ]; then
          cat > "${cfg.cloudflare.configFile}" <<'EOF'
        # Auto-generated by theyOS — backend will overwrite when public sites are added.
        ingress:
          - service: http_status:404
        EOF
          chown soyeht:soyeht "${cfg.cloudflare.configFile}"
          chmod 644 "${cfg.cloudflare.configFile}"
          echo "[theyos] Bootstrapped empty cloudflared config at ${cfg.cloudflare.configFile}"
        fi
        # Token dir: owned by soyeht (admin backend writes here on Settings →
        # Cloudflare → Enable), group soyeht with cfg.user as a member of that
        # group (configured via users.users.${cfg.user}.extraGroups above).
        # Mode 770 so cfg.user can both list the dir (cloudflared) and the
        # backend can write to it. Token file itself gets 640 from the backend.
        install -d -m 770 -o soyeht -g soyeht "$(dirname "${cfg.cloudflare.tokenFile}")"
      '');

      theyos-caddy-env = lib.mkIf cfg.caddy.enable (lib.stringAfter [ "users" ] ''
        if [ ! -f "${cfg.caddy.environmentFile}" ]; then
          mkdir -p "$(dirname "${cfg.caddy.environmentFile}")"
          cat > "${cfg.caddy.environmentFile}" <<'EOF'
        # Generated by theyos activation script.
        # Caddy reads this at service start. Edit then: systemctl restart caddy
        THEYOS_BASE_DOMAIN=${cfg.domain}
        ${if cfg.cloudflare.enable
          then "# CF_API_TOKEN= REQUIRED: set to your Cloudflare API token (Zone:DNS:Edit)"
          else "# CF_API_TOKEN= only needed if you flip cfg.cloudflare.enable = true"}
        EOF
          chmod 640 "${cfg.caddy.environmentFile}" 2>/dev/null || true
          chown caddy:caddy "${cfg.caddy.environmentFile}" 2>/dev/null || true
          echo "[theyos] Generated ${cfg.caddy.environmentFile} (THEYOS_BASE_DOMAIN=${cfg.domain})"
        fi
        ${lib.optionalString cfg.cloudflare.enable ''
          if [ -f "${cfg.caddy.environmentFile}" ] && \
             ! grep -q "^CF_API_TOKEN=" "${cfg.caddy.environmentFile}"; then
            echo "[theyos] WARNING: cfg.cloudflare.enable = true but CF_API_TOKEN is not set in ${cfg.caddy.environmentFile}"
            echo "[theyos]          Cloudflare DNS-01 cert issuance will fail until you add it."
          fi
        ''}
      '');

      # 2. Create directory structure + set ownership for the soyeht split.
      #
      # Ownership policy (see "Operational Access" in the user-split plan):
      #   - Runtime state paths (instances, goldens, snapshots, .run, logs,
      #     claws/data) → owned by soyeht:soyeht so the service process
      #     (which runs as User=soyeht) can read/write.
      #   - Base rootfs and SSH key are handled separately (see
      #     theyos-ssh-keys below; base rootfs is also corrected at service
      #     preStart to catch the first-boot ordering where
      #     theyos-rootfs-build runs as root).
      #   - claws/src stays cfg.user-owned because theyos-clone-claws still
      #     runs as cfg.user (it's an admin/repo operation, not a runtime one).
      #   - Home dir is chmod o+x so the soyeht user (outside /home/${cfg.user})
      #     can traverse into the firecracker/ subdirectory.
      #
      # Do NOT use `chown -R soyeht:soyeht /home/${cfg.user}/firecracker` —
      # the firecracker/assets/ directory contains symlinks into /nix/store
      # via theyos-assets, and chown without -h follows symlinks (it would
      # try to modify /nix/store files, which is read-only). Instead, chown
      # explicit subpaths.
      theyos-dirs = lib.stringAfter [ "users" "theyos-secrets" ] ''
        mkdir -p ${cfg.repoDir}/{.run,logs}
        mkdir -p ${cfg.repoDir}/claws/data/{picoclaw,zeroclaw,nanobot,openclaw,nullclaw,ironclaw}/customers
        mkdir -p ${cfg.repoDir}/claws/src
        mkdir -p /home/${cfg.user}/firecracker/{bin,assets,instances}
        mkdir -p /home/${cfg.user}/firecracker/assets/{goldens,snapshots}
        # golden-build is inside the repo (imagebuilder uses repo_root/firecracker/golden-build)
        mkdir -p ${cfg.repoDir}/firecracker/golden-build

        # Service-owned state paths — explicit subpaths only.
        chown soyeht:soyeht /home/${cfg.user}/firecracker 2>/dev/null || true
        chown soyeht:soyeht /home/${cfg.user}/firecracker/assets 2>/dev/null || true
        chown soyeht:soyeht /home/${cfg.user}/firecracker/bin 2>/dev/null || true
        chown -R soyeht:soyeht /home/${cfg.user}/firecracker/instances 2>/dev/null || true
        chown -R soyeht:soyeht /home/${cfg.user}/firecracker/assets/goldens 2>/dev/null || true
        chown -R soyeht:soyeht /home/${cfg.user}/firecracker/assets/snapshots 2>/dev/null || true
        chown -R soyeht:soyeht ${cfg.repoDir}/firecracker/golden-build 2>/dev/null || true

        # Base rootfs: single file produced by theyos-rootfs-build (if present).
        # The service preStart also unconditionally chowns these in case the
        # rootfs-build service runs AFTER activation.
        if [ -f /home/${cfg.user}/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4 ]; then
          chown soyeht:soyeht /home/${cfg.user}/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4
          chmod 0644 /home/${cfg.user}/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4
        fi

        # Runtime state paths in the repo checkout
        chown -R soyeht:soyeht ${cfg.repoDir}/.run ${cfg.repoDir}/logs 2>/dev/null || true
        chown -R soyeht:soyeht ${cfg.repoDir}/claws/data 2>/dev/null || true
        find ${cfg.repoDir}/claws/data -type d -exec chmod 0750 {} + 2>/dev/null || true

        # Admin-owned: clone-claws continues to run as cfg.user, so the
        # claws/src tree stays owned by the admin.
        chown -R ${cfg.user}:users ${cfg.repoDir}/claws/src 2>/dev/null || true

        # Ensure home dir is traversable so unshare --user --map-root-user
        # namespaces (imagebuilder, vmrunner) can reach firecracker assets,
        # AND so the soyeht service (which has HOME=/home/${cfg.user} in
        # the unit environment) can traverse into firecracker/. NixOS
        # defaults home dirs to 700; o+x allows traversal without listing.
        chmod o+x /home/${cfg.user}
      '';

      # 3. Generate SSH keypair (local, deterministic).
      #
      # Ownership/mode rationale:
      #   - Private key: 0400 soyeht:soyeht. OpenSSH refuses to use any
      #     private key that is readable by group or other, regardless of
      #     which uid the ssh process is running as — it enforces this
      #     before attempting any crypto operation. An earlier version of
      #     this module set 0440 soyeht:wheel on the assumption that
      #     giving the admin group-read would preserve a manual debug
      #     workflow; that was wrong on two counts: (1) the primary
      #     consumer is the ssh process launched by soyeht-admin-host
      #     (User=soyeht), and any group-read bit makes ssh reject the
      #     key outright, breaking every fc-ssh path; (2) admin debug
      #     does not need file-perm access — use `sudo -u soyeht ssh -i
      #     <key> root@127.0.0.1 -p <SSH_PORT>` (or `sudo cat` for
      #     inspection) instead.
      #   - Public key: 0644 soyeht:soyeht — world-readable (it's public).
      theyos-ssh-keys = lib.stringAfter [ "theyos-dirs" ] ''
        KEY="/home/${cfg.user}/firecracker/assets/ubuntu-24.04-root.id_rsa"
        if [ ! -f "$KEY" ]; then
          ${pkgs.openssh}/bin/ssh-keygen -t ed25519 -f "$KEY" -N "" -q
          echo "[theyos] Generated SSH keypair at $KEY"
        fi
        # Idempotent: always enforce ownership/mode even if file exists.
        if [ -f "$KEY" ]; then
          chown soyeht:soyeht "$KEY"
          chmod 0400 "$KEY"
        fi
        if [ -f "$KEY.pub" ]; then
          chown soyeht:soyeht "$KEY.pub"
          chmod 0644 "$KEY.pub"
        fi
      '';

      # 4. Symlink Nix-built Firecracker binaries + kernel (local, deterministic).
      theyos-assets = lib.stringAfter [ "theyos-dirs" ] ''
        ln -sf ${cfg.firecrackerPackage}/bin/firecracker /home/${cfg.user}/firecracker/bin/firecracker
        ln -sf ${cfg.firecrackerPackage}/bin/jailer /home/${cfg.user}/firecracker/bin/jailer
        ln -sf ${cfg.kernelPackage} /home/${cfg.user}/firecracker/assets/vmlinux-6.1.155
      '';

      # 5. Generate .env from .env.example template + module options + secrets.
      # Uses `soyeht render-env` as the single renderer: replaces uncommented
      # keys, uncomments commented keys, appends missing keys.
      theyos-env = lib.stringAfter [ "theyos-secrets" "theyos-dirs" ] ''
        # The runtime expects a live repo checkout at cfg.repoDir, but tests
        # (and broken host setups) may only have the runtime-owned directories.
        # Seed the canonical template into repoDir on first boot if it is
        # missing so `.env` generation stays deterministic.
        if [ ! -f ${cfg.repoDir}/.env.example ]; then
          install -D -m 0644 -o ${cfg.user} -g users ${../.env.example} ${cfg.repoDir}/.env.example
        fi

        PASSWORD="$(cat "${passwordFile}")"
        PEPPER="$(cat "${pepperFile}")"
        THEYOS_DIR=${cfg.repoDir} ${cfg.package}/bin/soyeht render-env \
          --template ${cfg.repoDir}/.env.example \
          --set SOYEHT_ADMIN_USER=admin \
          --set "SOYEHT_ADMIN_PASSWORD=$PASSWORD" \
          --set "THEYOS_SESSION_PEPPER=$PEPPER" \
          --set THEYOS_HOME=/home/${cfg.user} \
          --set ACCESS_MODE=${cfg.accessMode} \
          --set THEYOS_OWNER_AUTH_V2_ROLLOUT=${cfg.ownerAuthV2Rollout} \
          --set ADMIN_PORT=${toString cfg.adminPort} \
          --set THEYOS_BASE_DOMAIN=${cfg.domain} \
          --set THEYOS_BOOTSTRAP_TOKEN_PATH=${cfg.secretsDir}/bootstrap-token \
          --output ${cfg.repoDir}/.env
        # .env stays owned by cfg.user (the human admin edits it). systemd
        # reads EnvironmentFile= as root before dropping to User=soyeht, so
        # the soyeht service user does NOT need direct read access. Mode
        # 0600 keeps SOYEHT_ADMIN_PASSWORD out of reach of other users.
        chown ${cfg.user}:users ${cfg.repoDir}/.env
        chmod 0600 ${cfg.repoDir}/.env
      '';
    };

    # ── Systemd services ─────────────────────────────────────────────────────

    systemd.services.soyeht-admin-host = {
      description = "theyOS admin backend (Firecracker-first)";
      after = [ "network-online.target" ]
        ++ lib.optional cfg.caddy.enable "caddy.service";
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      path = with pkgs; [
        coreutils curl util-linux iproute2 iptables
        slirp4netns e2fsprogs cfg.package
        # `nc` is required by imagebuilder's setup_ssh_hostfwd to poke the
        # slirp4netns control socket during build-from-plan (Fase C).
        # TODO(theyos): replace with UnixStream (see vmrunner's
        # slirp_add_hostfwd) and drop this runtime dep.
        netcat-openbsd
      ];

      environment = {
        # KNOWN LIMITATION: HOME points at cfg.user's home because vmrunner
        # resolves ~/firecracker/... from $HOME at 6 hardcoded call sites
        # in admin/rust/vmrunner-rs/src/lib.rs (lines 928, 957, 1124, 1144,
        # 1187, 1192). Full isolation would require moving state to
        # /var/lib/theyos/, which is blocked by those hardcoded paths plus
        # the derivation at admin/rust/server-rs/src/main.rs:446. See the
        # user-split plan's "Known limitation aceita" section. The current
        # design splits identity (service runs as soyeht, not cfg.user)
        # without moving paths.
        HOME = "/home/${cfg.user}";
        THEYOS_DIR = cfg.repoDir;
        THEYOS_BIN_DIR = "${cfg.package}/bin";
        WEB_DIR = "${cfg.frontendPackage}";
      } // lib.optionalAttrs cfg.cloudflare.enable {
        # Cloudflared sync (consumed by admin/rust/server-rs/src/cloudflared_sync.rs).
        # When set, the backend regenerates the cloudflared config.yml on every
        # public-site change and reloads cloudflared via systemctl. Without
        # these vars the sync code is a silent no-op.
        THEYOS_CLOUDFLARED_CONFIG = cfg.cloudflare.configFile;
        # File paths the API-driven setup writes/reads (admin/rust/server-rs/
        # src/cloudflare_admin.rs). The backend places the operator's API
        # token in apiTokenFile and the connector token in tokenFile.
        THEYOS_CLOUDFLARED_TOKEN_FILE     = cfg.cloudflare.tokenFile;
        THEYOS_CLOUDFLARED_API_TOKEN_FILE = cfg.cloudflare.apiTokenFile;
        # /run/wrappers/bin/sudo is the setuid wrapper; the binary at
        # /run/current-system/sw/bin/sudo is a plain Nix-store file with no
        # setuid bit and refuses to run. The wrapped sudo uses the same
        # sudoers rules — see the soyeht NOPASSWD rule above.
        THEYOS_CLOUDFLARED_RELOAD_CMD  = "/run/wrappers/bin/sudo -n /run/current-system/sw/bin/systemctl reload cloudflared";
        THEYOS_CLOUDFLARED_START_CMD   = "/run/wrappers/bin/sudo -n /run/current-system/sw/bin/systemctl start cloudflared";
        THEYOS_CLOUDFLARED_STOP_CMD    = "/run/wrappers/bin/sudo -n /run/current-system/sw/bin/systemctl stop cloudflared";
        THEYOS_CLOUDFLARED_RESTART_CMD = "/run/wrappers/bin/sudo -n /run/current-system/sw/bin/systemctl restart cloudflared";
      };

      preStart = ''
        # Repair ownership before service start. Runs as root (systemd
        # PermissionsStartOnly = true). Targets soyeht:soyeht to catch:
        #   - drift from dev/manual operations
        #   - first-boot ordering where theyos-rootfs-build.service runs
        #     as root (no User=) and leaves the base rootfs owned by
        #     root:root because rootfsbuilder-rs/src/image.rs:78 uses
        #     SUDO_UID/UID which falls back to 0
        #   - any rollback-then-redeploy sequence where files were briefly
        #     owned by cfg.user and need to go back to soyeht
        #
        # The `find` is guarded by `! -type l` so it never follows symlinks
        # (firecracker/assets/ contains symlinks into /nix/store and we
        # absolutely must not try to modify store files).
        for root in \
          /home/${cfg.user}/firecracker/instances \
          /home/${cfg.user}/firecracker/assets/goldens \
          /home/${cfg.user}/firecracker/assets/snapshots \
          ${cfg.repoDir}/.run \
          ${cfg.repoDir}/logs
        do
          if [ -d "$root" ]; then
            find "$root" ! -type l \( ! -user soyeht -o ! -group soyeht \) \
              -exec chown soyeht:soyeht {} +
          fi
        done

        # Base rootfs file — not inside the dirs above, and first-boot
        # ordering means theyos-rootfs-build may land root-owned here.
        # Unconditional (idempotent) chown+chmod. Do NOT gate on
        # `stat -c %U` alone — that would skip cases where user is
        # already soyeht but group or mode drifted.
        for f in /home/${cfg.user}/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4 \
                 /home/${cfg.user}/firecracker/assets/ubuntu-24.04-rootfs.ext4
        do
          if [ -f "$f" ]; then
            chown soyeht:soyeht "$f"
            chmod 0644 "$f"
          fi
        done
      '';

      serviceConfig = {
        Type = "simple";
        PermissionsStartOnly = true;     # preStart runs as root
        User = "soyeht";
        Group = "soyeht";
        WorkingDirectory = cfg.repoDir;
        ExecStart = "${cfg.package}/bin/theyos-admin-host";
        EnvironmentFile = "${cfg.repoDir}/.env";
        # Explicit Firecracker state paths. fc-ssh (and other vmrunner
        # helpers) default to ${HOME}/firecracker/instances and
        # ${HOME}/firecracker/assets/ubuntu-24.04-root.id_rsa, which
        # works here only because .env renders HOME=/home/${cfg.user}.
        # Setting these explicitly removes the implicit HOME dependency:
        # any child process (including a future `runuser -u soyeht --
        # fc-ssh …` in a diagnostic subcommand) picks up the correct
        # paths without needing HOME to be set. Also self-documents the
        # unit — operators reading `systemctl show` see the path literal.
        Environment = [
          "FIRECRACKER_STATE_DIR=/home/${cfg.user}/firecracker/instances"
          "FIRECRACKER_SSH_KEY=/home/${cfg.user}/firecracker/assets/ubuntu-24.04-root.id_rsa"
        ];
        Restart = "always";
        RestartSec = "5s";
      };
    };

    # Cloudflare Tunnel (installed when cfg.cloudflare.enable, dormant until
    # the operator configures it via Settings → Cloudflare in the admin UI).
    #
    # ConditionPathExists keeps the unit from trying to start before there's
    # a connector token on disk. After enabling cloudflared in nix and
    # rebooting, `systemctl start cloudflared` is a silent no-op until the
    # backend writes ${cfg.cloudflare.tokenFile} during setup. This is what
    # lets the operator skip the SSH+nix dance entirely.
    systemd.services.cloudflared = lib.mkIf cfg.cloudflare.enable {
      description = "Cloudflare Tunnel";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      startLimitIntervalSec = 600;
      startLimitBurst = 3;

      unitConfig = {
        ConditionPathExists = cfg.cloudflare.tokenFile;
      };

      serviceConfig = {
        ExecStart = "${pkgs.cloudflared}/bin/cloudflared --no-autoupdate --metrics 127.0.0.1:2000 tunnel --config ${cfg.cloudflare.configFile} run --token-file ${cfg.cloudflare.tokenFile}";
        # Cloudflared reloads the ingress config on SIGHUP without dropping the
        # tunnel — used by the admin backend after every public-site change.
        ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        Restart = "always";
        RestartSec = "5s";
        Type = "simple";
        User = cfg.user;
        WorkingDirectory = cfg.repoDir;
      };
    };

    # Clone claw source repos (oneshot, NETWORK — not in activation).
    #
    # Previously this unit had
    #   unitConfig.ConditionPathExists = "!${cfg.repoDir}/claws/src/picoclaw/.git";
    # which prevented the service from ever running again once picoclaw was
    # cloned. When a new claw was added to the manifest (e.g. hermes-agent)
    # on an already-provisioned host, the clone never happened and the
    # Registry loaded incomplete — contributing to the "unsupported claw
    # type" HTTP 400 on mobile instance creation.
    #
    # The script is already idempotent (each git clone is guarded by
    # `[ -d X/.git ] ||`), so running it on every boot is a no-op when
    # everything is in place (~100ms stat dirs), and reconciles new claws
    # when the manifest grows. The ConditionPathExists is removed.
    systemd.services.theyos-clone-claws = {
      description = "Clone theyOS claw source repos";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      path = [ pkgs.git ];

      serviceConfig = {
        Type = "oneshot";
        User = cfg.user;
        WorkingDirectory = cfg.repoDir;
        ExecStart = pkgs.writeShellScript "clone-claws" ''
          cd ${cfg.repoDir}/claws/src
          [ -d picoclaw/.git ] || ${pkgs.git}/bin/git clone --depth 1 https://github.com/sipeed/picoclaw.git picoclaw 2>/dev/null || true
          [ -d zeroclaw/.git ] || ${pkgs.git}/bin/git clone --depth 1 https://github.com/openagen/zeroclaw.git zeroclaw 2>/dev/null || true
          [ -d nanobot/.git ]  || ${pkgs.git}/bin/git clone --depth 1 https://github.com/HKUDS/nanobot.git nanobot 2>/dev/null || true
          mkdir -p openclaw nullclaw ironclaw
        '';
      };
    };

    # Build base rootfs (oneshot, NETWORK+ROOT — only if missing).
    systemd.services.theyos-rootfs-build = {
      description = "Build theyOS base rootfs";
      after = [ "network-online.target" "theyos-clone-claws.service" ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      path = with pkgs; [
        debootstrap e2fsprogs coreutils openssh cfg.package
        util-linux  # mount, umount, losetup
        gnutar gzip
        gnused gnugrep
        findutils
        bash
      ];

      unitConfig.ConditionPathExists = "!/home/${cfg.user}/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4";

      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${cfg.package}/bin/rootfsbuilder";
        Environment = [
          "HOME=/home/${cfg.user}"
          "THEYOS_DIR=${cfg.repoDir}"
        ];
        TimeoutStartSec = "600";
      };
    };

    # Golden image builds are now managed via the Claw Store in the admin panel.
    # Users install/uninstall claw types on demand from /claws.
    # The old automatic rebuild timer has been removed.

    # Daily backup.
    systemd.services.daily-backup = {
      description = "theyOS daily backup";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      path = with pkgs; [ git gnutar gzip coreutils ];

      serviceConfig = {
        Type = "oneshot";
        User = cfg.user;
        WorkingDirectory = cfg.repoDir;
        # `soyeht backup` refuses to run without THEYOS_DIR set. WorkingDirectory
        # alone is not sufficient — the CLI explicitly reads THEYOS_DIR from the
        # environment. Same class of bug as commit 08a2e0d ("Preserve THEYOS_DIR
        # in install worker sudo env"), just on a different service.
        Environment = [ "THEYOS_DIR=${cfg.repoDir}" ];
        ExecStart = "${cfg.package}/bin/soyeht backup";
      };
    };

    systemd.timers.daily-backup = {
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = "02:00";
        Persistent = true;
      };
    };

    # Health check.
    systemd.services.app-healthcheck = {
      description = "theyOS health check";
      after = [ "soyeht-admin-host.service" ];

      path = with pkgs; [ curl coreutils bash ];

      script = ''
        set -euo pipefail
        if curl -fs --max-time 20 http://localhost:${toString cfg.adminPort}/healthz >/dev/null; then
          echo "[healthcheck] admin panel OK"
        else
          echo "[healthcheck] admin panel DOWN"
          exit 1
        fi
      '';

      serviceConfig = {
        Type = "oneshot";
        User = "root";
      };
    };

    systemd.timers.app-healthcheck = {
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnBootSec = "3m";
        OnUnitActiveSec = "5m";
        Persistent = true;
      };
    };
  };
}
