{
  description = "theyOS — multi-tenant AI assistant platform";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    crane.url = "github:ipetkov/crane";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, rust-overlay, crane, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ rust-overlay.overlays.default ];
        };
        rustToolchain = pkgs.rust-bin.stable."1.92.0".default;
        craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;
        theyosRuntime = import ./nix/packages/rust-workspace.nix {
          inherit pkgs craneLib;
          packageName = "theyos-runtime";
          # imagebuilder-rs is included: install_worker spawns it on-demand
          # when a user installs a tier=available claw that needs build-from-plan.
          excludedMembers = [ "vmrunner-macos-rs" "e2e-rs" ];
        };
        theyosBuilder = import ./nix/packages/rust-workspace.nix {
          inherit pkgs craneLib;
          packageName = "theyos-builder";
          excludedMembers = [ "vmrunner-macos-rs" ];
        };
      in {
        packages = rec {
          firecracker = import ./nix/packages/firecracker.nix { inherit pkgs; };
          firecracker-kernel = import ./nix/packages/kernel.nix { inherit pkgs; };
          theyos-runtime = theyosRuntime;
          theyos-builder = theyosBuilder;
          theyos-admin = theyos-runtime;
          theyos-frontend = import ./nix/packages/frontend.nix { inherit pkgs; };
          default = theyos-runtime;
        };
      }
    ) // {
      # NixOS module — import with: services.theyos.enable = true;
      nixosModules.theyos = import ./nix/module.nix self;

      # Default NixOS configuration.
      # Composed from machine-specific files generated by ./install-nixos:
      #   nix/hardware-configuration.nix — copied from /etc/nixos/
      #   nix/base-configuration.nix — copied from /etc/nixos/configuration.nix (user's existing config)
      #   nix/host.nix — theyOS service settings, generated from nix/host.nix.template
      # NOTE: x86_64-linux only — Firecracker requires KVM on x86_64.
      nixosConfigurations.theyos = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit self; };
        modules = [
          ./nix/hardware-configuration.nix
          ./nix/base-configuration.nix
          self.nixosModules.theyos
          ./nix/host.nix
        ];
      };

      # E2E installation test — boots a NixOS VM, applies theyOS module,
      # verifies services start, healthz works, and soyeht pair generates QR.
      # Run: nix build .#checks.x86_64-linux.install-test (x86_64-linux only)
      checks.x86_64-linux.install-test =
        let
          pkgs = import nixpkgs {
            system = "x86_64-linux";
            config = {
              allowUnfreePredicate = pkg:
                builtins.elem (nixpkgs.lib.getName pkg) [ "claude-code" ];
            };
          };
        in pkgs.testers.nixosTest {
          name = "theyos-install";

          nodes.server = { config, pkgs, ... }: {
            imports = [ self.nixosModules.theyos ];

            services.theyos = {
              enable = true;
              user = "testuser";
              repoDir = "/home/testuser/theyos";
              domain = "localhost";
              accessMode = "local";
              package = self.packages.x86_64-linux.theyos-runtime;
              frontendPackage = self.packages.x86_64-linux.theyos-frontend;
              firecrackerPackage = self.packages.x86_64-linux.firecracker;
              kernelPackage = self.packages.x86_64-linux.firecracker-kernel;
            };

            users.users.testuser = {
              isNormalUser = true;
              extraGroups = [ "wheel" ];
            };

            virtualisation = {
              memorySize = 2048;
              diskSize = 4096;
              cores = 2;
            };
          };

          testScript = ''
            import json

            start_all()

            with subtest("System boots"):
                server.wait_for_unit("multi-user.target")

            with subtest("Secrets generated"):
                server.succeed("test -f /var/lib/theyos/secrets/admin-password")
                server.succeed("test -f /var/lib/theyos/secrets/session-pepper")
                server.succeed("test -f /var/lib/theyos/secrets/bootstrap-token")

            with subtest("Directory structure"):
                server.succeed("test -d /home/testuser/theyos/claws/data/picoclaw/customers")

            with subtest(".env generated"):
                server.succeed("test -f /home/testuser/theyos/.env")
                server.succeed("grep -q 'ACCESS_MODE=local' /home/testuser/theyos/.env")

            with subtest("soyeht on PATH"):
                server.succeed("which soyeht")

            with subtest("Admin backend starts"):
                server.wait_for_unit("soyeht-admin-host.service", timeout=60)

            with subtest("Healthz OK"):
                server.wait_until_succeeds("curl -sf http://localhost:8892/healthz", timeout=30)

            with subtest("soyeht pair"):
                result = server.succeed(
                    "THEYOS_DIR=/home/testuser/theyos "
                    "THEYOS_BOOTSTRAP_TOKEN_PATH=/var/lib/theyos/secrets/bootstrap-token "
                    "THEYOS_ADMIN_URL=http://localhost:8892 "
                    "soyeht pair 2>&1 || true"
                )
                assert "theyos://pair" in result or "QR" in result, \
                    f"soyeht pair failed: {result[:500]}"

            with subtest("Pair token API"):
                token = server.succeed("cat /var/lib/theyos/secrets/bootstrap-token").strip()
                result = server.succeed(
                    f"curl -sf -X POST http://localhost:8892/api/v1/mobile/pair-token "
                    f"-H 'Authorization: Bearer {token}'"
                )
                data = json.loads(result)
                assert "deep_link" in data, f"Missing deep_link: {data}"
                assert data["deep_link"].startswith("theyos://pair"), \
                    f"Wrong deep_link: {data['deep_link']}"

            with subtest("AI CLIs installed"):
                server.succeed("which claude")
                server.succeed("which codex")
                server.succeed("which opencode")

            # ── soyeht user split asserts (post-cutover) ────────────────
            # See /Users/dev/.claude/plans/logical-jingling-orbit.md
            # for context on the service user split. These asserts verify
            # the cutover landed correctly: soyeht user exists with
            # nologin shell, the service runs as soyeht, state paths are
            # owned by soyeht:soyeht, the SSH key is readable by wheel,
            # and the narrow sudoers rule is in place.

            with subtest("soyeht service user exists with nologin"):
                server.succeed("id soyeht")
                server.succeed("getent group soyeht")
                shell = server.succeed("getent passwd soyeht | cut -d: -f7").strip()
                assert "nologin" in shell, \
                    f"soyeht shell should be nologin, got: {shell}"

            with subtest("Service runs as soyeht"):
                user = server.succeed(
                    "systemctl show soyeht-admin-host -p User --value"
                ).strip()
                group = server.succeed(
                    "systemctl show soyeht-admin-host -p Group --value"
                ).strip()
                assert user == "soyeht", f"expected User=soyeht, got: {user}"
                assert group == "soyeht", f"expected Group=soyeht, got: {group}"

            with subtest("State ownership — firecracker/instances"):
                owner = server.succeed(
                    "stat -c '%U:%G' /home/testuser/firecracker/instances"
                ).strip()
                assert owner == "soyeht:soyeht", \
                    f"instances owner should be soyeht:soyeht, got: {owner}"

            with subtest("State ownership — SSH key (soyeht:wheel 0440)"):
                info = server.succeed(
                    "stat -c '%U:%G %a' /home/testuser/firecracker/assets/ubuntu-24.04-root.id_rsa"
                ).strip()
                assert info == "soyeht:wheel 440", \
                    f"SSH key should be soyeht:wheel 440, got: {info}"

            with subtest(".env stays cfg.user-owned 0600"):
                # Systemd reads .env as root via EnvironmentFile=, then
                # drops to User=soyeht. The file does NOT need to be
                # readable by soyeht directly, so we keep it tight.
                info = server.succeed(
                    "stat -c '%U:%G %a' /home/testuser/theyos/.env"
                ).strip()
                assert info.startswith("testuser:") and info.endswith(" 600"), \
                    f".env should be testuser:* 600, got: {info}"

            with subtest("soyeht has narrow sudoers (nsenter only)"):
                # `sudo -l` output should list ONLY nsenter. Anything else
                # means either the narrow rule didn't apply or a fallback
                # (NOPASSWD: ALL) was used.
                output = server.succeed("sudo -u soyeht sudo -l -n 2>&1")
                assert "nsenter" in output, \
                    f"soyeht sudoers should allow nsenter, got: {output}"
                assert "NOPASSWD: ALL" not in output, \
                    f"soyeht should NOT have NOPASSWD: ALL, got: {output}"

            with subtest("preStart repairs ownership and mode drift"):
                server.succeed(
                    "mkdir -p /home/testuser/firecracker/assets/goldens/.prestart-drift "
                    "/home/testuser/firecracker/assets/snapshots/.prestart-drift"
                )
                server.succeed("touch /home/testuser/firecracker/instances/.prestart-drift")
                server.succeed("touch /home/testuser/theyos/.run/.prestart-drift")
                server.succeed("touch /home/testuser/theyos/logs/.prestart-drift")
                server.succeed("touch /home/testuser/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4")

                # Inject drift that the service preStart is supposed to repair.
                server.succeed(
                    "chown root:root "
                    "/home/testuser/firecracker/instances/.prestart-drift "
                    "/home/testuser/theyos/.run/.prestart-drift "
                    "/home/testuser/theyos/logs/.prestart-drift "
                    "/home/testuser/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4"
                )
                server.succeed(
                    "chown -R root:root "
                    "/home/testuser/firecracker/assets/goldens/.prestart-drift "
                    "/home/testuser/firecracker/assets/snapshots/.prestart-drift"
                )
                server.succeed("chmod 0600 /home/testuser/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4")

                server.succeed("systemctl restart soyeht-admin-host.service")
                server.wait_for_unit("soyeht-admin-host.service", timeout=60)
                server.wait_until_succeeds("curl -sf http://localhost:8892/healthz", timeout=30)

                repaired = server.succeed(
                    "stat -c '%U:%G' "
                    "/home/testuser/firecracker/instances/.prestart-drift "
                    "/home/testuser/firecracker/assets/goldens/.prestart-drift "
                    "/home/testuser/firecracker/assets/snapshots/.prestart-drift "
                    "/home/testuser/theyos/.run/.prestart-drift "
                    "/home/testuser/theyos/logs/.prestart-drift"
                )
                for line in repaired.strip().splitlines():
                    assert line == "soyeht:soyeht", \
                        f"preStart should repair drift to soyeht:soyeht, got: {line}"

                rootfs_info = server.succeed(
                    "stat -c '%U:%G %a' /home/testuser/firecracker/assets/ubuntu-24.04-rootfs-v2.ext4"
                ).strip()
                assert rootfs_info == "soyeht:soyeht 644", \
                    f"preStart should repair base rootfs to soyeht:soyeht 644, got: {rootfs_info}"
          '';
        };
    };
}
