//! NixOS mode detection and systemd helpers.

use std::path::Path;
use std::process::Command;

/// Returns true if this installation is NixOS-managed via `./install-nixos`.
///
/// Detection requires BOTH:
///   1. The system is NixOS (`/etc/NIXOS` exists)
///   2. `nix/host.nix` exists in the repo root — this file is generated by
///      `./install-nixos` on first run and is gitignored. A plain git checkout
///      on a NixOS dev machine will NOT have it, so the repo-based flow
///      (build/deploy/update) keeps working for developers.
pub fn is_nixos_managed(root: &Path) -> bool {
    Path::new("/etc/NIXOS").exists() && root.join("nix/host.nix").is_file()
}

/// If NixOS-managed, print a message and exit. Otherwise, return normally.
pub fn exit_nixos_managed(root: &Path, cmd_name: &str) {
    if is_nixos_managed(root) {
        eprintln!("[soyeht] '{cmd_name}' is not used on NixOS-managed installations.");
        eprintln!(
            "[soyeht] Use: cd {} && git pull && ./install-nixos",
            root.display()
        );
        std::process::exit(0);
    }
}

/// Returns `true` if the current process is running with effective UID 0.
///
/// Wraps the single `libc::geteuid()` syscall we need, so the
/// `#[allow(unsafe_code)]` lives in exactly one place.
#[allow(unsafe_code)]
fn is_euid_root() -> bool {
    // SAFETY: `geteuid` is a thread-safe read-only syscall that returns the
    // calling process's effective UID. No arguments, no error path, no
    // state, no memory aliasing.
    let euid = unsafe { libc::geteuid() };
    euid == 0
}

/// Run `git pull` + `nixos-rebuild switch --flake` to update a NixOS-managed
/// installation.
///
/// Handles two privilege paths:
///   - Production flow (`sudo soyeht update`): soyeht runs as root. Git ops
///     are downgraded to `$SUDO_USER` via `runuser` so files written (the
///     git index, `FETCH_HEAD`, tracked files modified by the fast-forward)
///     stay owned by the real user. `nixos-rebuild` is called DIRECTLY (no
///     inner sudo), avoiding nested-sudo that would rewrite `SUDO_UID=0`
///     and trip Nix's libgit2 "dubious ownership" guard (CVE-2022-24765)
///     on the flake fetch.
///   - Dev flow (bare `soyeht update`): soyeht runs as the user. Git ops
///     run directly; `nixos-rebuild` is wrapped in sudo.
pub fn nixos_update(root: &Path) {
    println!("[soyeht] NixOS mode: updating via git pull + nixos-rebuild...");

    let already_root = is_euid_root();

    // When running as root, determine who to drop privileges to for git ops.
    // Prefer SUDO_USER, but fall back to resolving SUDO_UID through the passwd
    // database so `sudo soyeht update` stays robust even when the host's sudo
    // policy omits one of the textual env vars.
    let real_user: Option<String> = if already_root {
        if let Some(u) = core_rs::env::sudo_invoker_user() {
            Some(u)
        } else {
            eprintln!(
                "[soyeht] error: running as root but the sudo invoker could not be resolved.\n\
                 [soyeht] `soyeht update` needs SUDO_USER or SUDO_UID so it can\n\
                 [soyeht] run git as the repo owner. Run as: sudo soyeht update"
            );
            std::process::exit(1);
        }
    } else {
        None
    };

    // Helper that builds a git command, downgrading to the repo owner via
    // `runuser` when we're running as root. `runuser` is preferred over
    // `sudo -u` because it doesn't nest sudo and doesn't touch SUDO_UID.
    let build_git = |args: &[&str]| -> Command {
        if let Some(user) = real_user.as_deref() {
            let mut cmd = Command::new("runuser");
            cmd.args(["-u", user, "--", "git"]);
            cmd.args(args);
            cmd
        } else {
            let mut cmd = Command::new("git");
            cmd.args(args);
            cmd
        }
    };

    let root_str = root.display().to_string();

    // 1. git pull (as repo owner)
    println!("[soyeht] Pulling latest changes...");
    let pull = build_git(&["-C", &root_str, "pull", "--ff-only"]).status();
    match pull {
        Ok(s) if s.success() => {}
        Ok(s) => {
            eprintln!(
                "[soyeht] git pull failed (exit {}). Is the working tree clean?",
                s.code().unwrap_or(1)
            );
            std::process::exit(1);
        }
        Err(e) => {
            eprintln!("[soyeht] failed to run git: {e}");
            std::process::exit(1);
        }
    }

    // 2. Ensure flake files are tracked (as repo owner).
    //    Fail loud on error — these files MUST be in the git index for the
    //    flake to pick them up. A silent drop here could leave
    //    nixos-rebuild reading stale content.
    let add = build_git(&[
        "-C",
        &root_str,
        "add",
        "-f",
        "nix/host.nix",
        "nix/hardware-configuration.nix",
        "nix/base-configuration.nix",
    ])
    .status();
    match add {
        Ok(s) if s.success() => {}
        Ok(s) => {
            eprintln!(
                "[soyeht] git add -f failed (exit {}). Are the flake files present?",
                s.code().unwrap_or(1)
            );
            std::process::exit(1);
        }
        Err(e) => {
            eprintln!("[soyeht] failed to run git add: {e}");
            std::process::exit(1);
        }
    }

    // 3. nixos-rebuild switch --flake <root>#theyos
    //    Direct exec when already root (no nested sudo).
    //    Wrap in sudo only for the non-root dev flow.
    let flake_ref = format!("{}#theyos", root.display());
    println!("[soyeht] Rebuilding NixOS configuration...");
    println!("[soyeht] This may take a few minutes.\n");
    let rebuild = if already_root {
        Command::new("nixos-rebuild")
            .args(["switch", "--flake", &flake_ref])
            .status()
    } else {
        Command::new("sudo")
            .args(["nixos-rebuild", "switch", "--flake", &flake_ref])
            .status()
    };
    match rebuild {
        Ok(s) if s.success() => {
            println!("\n[soyeht] Update complete.");
        }
        Ok(s) => {
            eprintln!(
                "\n[soyeht] nixos-rebuild failed (exit {}).",
                s.code().unwrap_or(1)
            );
            std::process::exit(1);
        }
        Err(e) => {
            eprintln!("[soyeht] failed to run nixos-rebuild: {e}");
            std::process::exit(1);
        }
    }
}

/// Run `systemctl <args>`. Exits with error if the command fails (e.g.
/// permission denied, unit not found).
pub fn systemctl_or_exit(args: &[&str]) {
    let status = Command::new("systemctl").args(args).status();
    match status {
        Ok(s) if s.success() => {}
        Ok(s) => {
            let code = s.code().unwrap_or(1);
            eprintln!("[soyeht] systemctl {} failed (exit {code})", args.join(" "));
            if code == 4 || code == 5 {
                // 4 = unit not found, 5 = no such process / not loaded
                eprintln!(
                    "[soyeht] Has ./install-nixos been run? The systemd unit may not be installed."
                );
            } else {
                eprintln!("[soyeht] Try: sudo systemctl {}", args.join(" "));
            }
            std::process::exit(1);
        }
        Err(e) => {
            eprintln!("[soyeht] failed to run systemctl: {e}");
            std::process::exit(1);
        }
    }
}
