//! Render `.env` from `.env.example` template + key-value overrides.
//!
//! Used by:
//! - `soyeht render-env` CLI subcommand
//! - NixOS module activation script (`module.nix`)
//! - `install-nixos` fallback

use std::collections::HashMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

/// Render `.env` content from a template file and a set of key-value overrides.
///
/// For each override key, the renderer handles three cases:
/// 1. **Uncommented line** (`KEY=value`) → replace the value
/// 2. **Commented line** (`# KEY=value`) → uncomment and replace the value
/// 3. **Missing key** → append `KEY=value` at the end
///
/// Lines without matching overrides are preserved as-is (including comments).
pub fn render(template: &str, overrides: &HashMap<String, String>) -> String {
    let ts_str = core_rs::time::now_iso_secs();
    let mut out = format!("# Generated by soyeht render-env on {ts_str}\n");
    out.push_str("# Source template: .env.example\n\n");

    let mut materialized: HashMap<&str, bool> = HashMap::new();

    for line in template.lines() {
        let trimmed = line.trim();

        // Empty line → preserve
        if trimmed.is_empty() {
            out.push('\n');
            continue;
        }

        // Commented KEY=VALUE line — check if we have an override to uncomment it
        if let Some(rest) = trimmed.strip_prefix('#') {
            let rest = rest.trim_start();
            if let Some((key, _)) = rest.split_once('=') {
                let key = key.trim();
                if let Some(value) = overrides.get(key) {
                    out.push_str(key);
                    out.push('=');
                    out.push_str(value);
                    out.push('\n');
                    materialized.insert(key, true);
                    continue;
                }
            }
            // No override for this commented key — preserve as-is
            out.push_str(line);
            out.push('\n');
            continue;
        }

        // Uncommented KEY=VALUE line
        if let Some((key, _)) = trimmed.split_once('=') {
            let key = key.trim();
            if let Some(value) = overrides.get(key) {
                out.push_str(key);
                out.push('=');
                out.push_str(value);
                out.push('\n');
                materialized.insert(key, true);
            } else {
                out.push_str(line);
                out.push('\n');
            }
            continue;
        }

        // Not a KEY=VALUE or comment — keep as-is
        out.push_str(line);
        out.push('\n');
    }

    // Case 3: append keys that weren't found in the template at all
    let mut appended = Vec::new();
    for (key, value) in overrides {
        if !materialized.contains_key(key.as_str()) {
            appended.push((key.as_str(), value.as_str()));
        }
    }
    if !appended.is_empty() {
        appended.sort_by_key(|(k, _)| *k);
        out.push_str("\n# Additional keys (not in .env.example template)\n");
        for (key, value) in appended {
            out.push_str(key);
            out.push('=');
            out.push_str(value);
            out.push('\n');
        }
    }

    out
}

/// CLI entry point for `soyeht render-env`.
pub fn cmd_render_env(root: &Path, args: &super::cli::RenderEnvArgs) {
    let template_path = args
        .template
        .clone()
        .unwrap_or_else(|| root.join(".env.example").to_string_lossy().into_owned());

    let template = match fs::read_to_string(&template_path) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("[render-env] error: could not read template {template_path}: {e}");
            std::process::exit(1);
        }
    };

    let mut overrides = HashMap::new();
    for pair in &args.set {
        if let Some((key, value)) = pair.split_once('=') {
            overrides.insert(key.to_string(), value.to_string());
        } else {
            eprintln!("[render-env] error: invalid --set format: {pair}");
            eprintln!("[render-env] expected: --set KEY=VALUE");
            std::process::exit(1);
        }
    }

    let rendered = render(&template, &overrides);

    let output_path = args
        .output
        .clone()
        .unwrap_or_else(|| root.join(".env").to_string_lossy().into_owned());

    if let Err(e) = fs::write(&output_path, &rendered) {
        eprintln!("[render-env] error: could not write {output_path}: {e}");
        std::process::exit(1);
    }
    if let Err(e) = fs::set_permissions(&output_path, fs::Permissions::from_mode(0o600)) {
        eprintln!("[render-env] warning: could not chmod 600 {output_path}: {e}");
    }
    println!("[render-env] wrote {output_path}");
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_overrides(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    #[test]
    fn replace_uncommented_key() {
        let template = "ADMIN_PORT=8892\nRUST_LOG=info\n";
        let overrides = make_overrides(&[("ADMIN_PORT", "9000")]);
        let result = render(template, &overrides);
        assert!(result.contains("ADMIN_PORT=9000"), "should replace value");
        assert!(result.contains("RUST_LOG=info"), "should keep unmatched");
    }

    #[test]
    fn uncomment_and_replace() {
        let template = "# ADMIN_PORT=8892\nRUST_LOG=info\n";
        let overrides = make_overrides(&[("ADMIN_PORT", "9000")]);
        let result = render(template, &overrides);
        assert!(
            result.contains("ADMIN_PORT=9000"),
            "should uncomment and replace"
        );
        assert!(
            !result.contains("# ADMIN_PORT"),
            "commented line should be gone"
        );
    }

    #[test]
    fn append_missing_key() {
        let template = "RUST_LOG=info\n";
        let overrides = make_overrides(&[("THEYOS_BASE_DOMAIN", "example.com")]);
        let result = render(template, &overrides);
        assert!(result.contains("RUST_LOG=info"), "should keep existing");
        assert!(
            result.contains("THEYOS_BASE_DOMAIN=example.com"),
            "should append missing key"
        );
        assert!(
            result.contains("# Additional keys"),
            "should have append section header"
        );
    }

    #[test]
    fn all_three_cases_together() {
        let template = "\
SOYEHT_ADMIN_PASSWORD=CHANGE_ME
# ADMIN_PORT=8892
RUST_LOG=info
";
        let overrides = make_overrides(&[
            ("SOYEHT_ADMIN_PASSWORD", "secret123"),
            ("ADMIN_PORT", "9000"),
            ("THEYOS_BASE_DOMAIN", "test.com"),
        ]);
        let result = render(template, &overrides);

        // Case 1: replaced
        assert!(result.contains("SOYEHT_ADMIN_PASSWORD=secret123"));
        // Case 2: uncommented
        assert!(result.contains("ADMIN_PORT=9000"));
        assert!(!result.contains("# ADMIN_PORT"));
        // Case 3: appended
        assert!(result.contains("THEYOS_BASE_DOMAIN=test.com"));
        // Untouched
        assert!(result.contains("RUST_LOG=info"));
    }

    #[test]
    fn preserves_comments_and_empty_lines() {
        let template = "\
# This is a section header
# Another comment

RUST_LOG=info

# Optional stuff
# OPENROUTER_API_KEY=YOUR_KEY
";
        let overrides = make_overrides(&[]);
        let result = render(template, &overrides);

        assert!(result.contains("# This is a section header"));
        assert!(result.contains("# Another comment"));
        assert!(result.contains("# Optional stuff"));
        assert!(result.contains("# OPENROUTER_API_KEY=YOUR_KEY"));
        assert!(result.contains("RUST_LOG=info"));
    }

    #[test]
    fn no_duplicate_when_commented_and_uncommented() {
        // If a key appears both commented and uncommented, only the uncommented
        // version is replaced. The commented one stays as documentation.
        let template = "\
# ADMIN_PORT=8892
ADMIN_PORT=8892
";
        let overrides = make_overrides(&[("ADMIN_PORT", "9000")]);
        let result = render(template, &overrides);

        // Both occurrences should resolve — commented gets uncommented,
        // uncommented gets replaced. The key appears twice with the override.
        let count = result.matches("ADMIN_PORT=9000").count();
        assert_eq!(count, 2, "both occurrences should be replaced");
    }

    #[test]
    fn handles_spaces_around_equals() {
        let template = "ADMIN_PORT =8892\n";
        let overrides = make_overrides(&[("ADMIN_PORT", "9000")]);
        let result = render(template, &overrides);
        // Key has trailing space trimmed during matching
        assert!(result.contains("ADMIN_PORT=9000"));
    }

    #[test]
    fn override_with_empty_value() {
        let template = "RUST_LOG=info\n";
        let overrides = make_overrides(&[("RUST_LOG", "")]);
        let result = render(template, &overrides);
        assert!(result.contains("RUST_LOG=\n") || result.contains("RUST_LOG=\n"));
    }

    #[test]
    fn cmd_render_env_writes_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();

        fs::write(
            root.join(".env.example"),
            "SOYEHT_ADMIN_PASSWORD=CHANGE_ME\n# ADMIN_PORT=8892\nRUST_LOG=info\n",
        )
        .unwrap();

        let args = super::super::cli::RenderEnvArgs {
            template: None,
            output: Some(root.join(".env").to_string_lossy().into_owned()),
            set: vec![
                "SOYEHT_ADMIN_PASSWORD=mypass".to_string(),
                "ADMIN_PORT=9000".to_string(),
            ],
        };

        cmd_render_env(root, &args);

        let content = fs::read_to_string(root.join(".env")).unwrap();
        assert!(content.contains("SOYEHT_ADMIN_PASSWORD=mypass"));
        assert!(content.contains("ADMIN_PORT=9000"));
        assert!(content.contains("RUST_LOG=info"));

        // Check permissions
        let perms = fs::metadata(root.join(".env")).unwrap().permissions();
        assert_eq!(perms.mode() & 0o777, 0o600);
    }
}
