//! A2 Noise machinery, promoted to production (S2 responder slice a). The
//! harness delegates to these — ONE implementation of the protocol, both
//! sides. Protocol constants are pinned by the frozen A2-R1 corpus:
//! `Noise_XXa2v1_25519_ChaChaPoly_SHA256`, prologue label, domain/version.
//!
//! Production uses a FRESH ephemeral per channel (the harness pins a fixed
//! one for its KATs via Snow's `fixed_ephemeral_key_for_testing_only` —
//! test-only by the API's own name; peers read the ephemeral from the wire
//! and do not care how it was chosen).

use snow::{Builder, HandshakeState};
use zeroize::{Zeroize, Zeroizing};

use crate::owner_site_authority::OwnerSiteAuthorityError;
use crate::owner_site_binding_glue::{A2_DOMAIN, hash_canonical};

#[allow(dead_code)]
pub(crate) const A2_VERSION: u8 = 1;
pub(crate) const NOISE_PUBLIC_KEY_BYTES: usize = 32;
#[allow(dead_code)]
pub(crate) const MAX_A2_FRAME_BYTES: usize = 16 * 1024;
const A2_NOISE_PROTOCOL_NAME: &str = "Noise_XXa2v1_25519_ChaChaPoly_SHA256";
const A2_NOISE_PROLOGUE_LABEL: &str = "noise-prologue";
const A2_RECORD_PROFILE: &str = "a2-record-v1";

pub(crate) fn noise_params() -> snow::params::NoiseParams {
    use snow::params::{BaseChoice, CipherChoice, DHChoice, HandshakeChoice, HandshakePattern};
    snow::params::NoiseParams::new(
        A2_NOISE_PROTOCOL_NAME.to_owned(),
        BaseChoice::Noise,
        HandshakeChoice {
            pattern: HandshakePattern::XX,
            modifiers: snow::params::HandshakeModifierList { list: Vec::new() },
        },
        DHChoice::Curve25519,
        CipherChoice::ChaChaPoly,
        snow::params::HashChoice::SHA256,
    )
}

pub(crate) fn array_32(bytes: &[u8]) -> Result<[u8; 32], OwnerSiteAuthorityError> {
    bytes
        .try_into()
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)
}

/// The A2 prologue is a canonical CBOR TUPLE of five elements — NOT a hash.
/// Byte-exact with the harness: change this and every peer fails.
pub(crate) fn a2_noise_prologue() -> Result<Vec<u8>, OwnerSiteAuthorityError> {
    household_rs::cbor::to_canonical_vec(&(
        A2_DOMAIN,
        A2_NOISE_PROLOGUE_LABEL,
        A2_VERSION,
        A2_RECORD_PROFILE,
        A2_NOISE_PROTOCOL_NAME,
    ))
    .map_err(|_| OwnerSiteAuthorityError::CborEncode)
}

pub(crate) fn a2_noise_builder(prologue: &[u8]) -> Result<Builder<'_>, OwnerSiteAuthorityError> {
    Builder::new(noise_params())
        .prologue(prologue)
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)
}

/// Fresh static keypair for one responder session (private half zeroized on
/// drop; never leaves this module as anything but Snow key material).
#[allow(dead_code)]
pub(crate) fn new_noise_static_keypair()
-> Result<(Zeroizing<Vec<u8>>, [u8; NOISE_PUBLIC_KEY_BYTES]), OwnerSiteAuthorityError> {
    let builder = Builder::new(noise_params());
    let mut keypair = builder
        .generate_keypair()
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)?;
    let public = array_32(&keypair.public)?;
    let private = Zeroizing::new(std::mem::take(&mut keypair.private));
    keypair.private.zeroize();
    Ok((private, public))
}

/// Build the responder handshake with the session's static private key and a
/// FRESH ephemeral secret generated by the caller per channel.
#[allow(dead_code)]
pub(crate) fn responder_with_channel_keys(
    static_private: &[u8],
    ephemeral_private: &[u8],
) -> Result<HandshakeState, OwnerSiteAuthorityError> {
    let prologue = a2_noise_prologue()?;
    a2_noise_builder(&prologue)?
        .local_private_key(static_private)
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)?
        .fixed_ephemeral_key_for_testing_only(ephemeral_private)
        .build_responder()
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)
}

#[allow(dead_code)]
pub(crate) fn noise_public_prefix(
    noise: &[u8],
) -> Result<[u8; NOISE_PUBLIC_KEY_BYTES], OwnerSiteAuthorityError> {
    array_32(
        noise
            .get(..NOISE_PUBLIC_KEY_BYTES)
            .ok_or(OwnerSiteAuthorityError::CborEncode)?,
    )
}

#[derive(serde::Serialize)]
struct ServerAuthTranscript<'a>(
    &'a str,
    &'a str,
    #[serde(with = "serde_bytes")] &'a [u8],
    #[serde(with = "serde_bytes")] &'a [u8],
    #[serde(with = "serde_bytes")] &'a [u8],
    #[serde(with = "serde_bytes")] &'a [u8],
    &'a str,
    #[serde(with = "serde_bytes")] &'a [u8],
    u64,
    #[serde(with = "serde_bytes")] &'a [u8],
    #[serde(with = "serde_bytes")] &'a [u8],
    u64,
    #[serde(with = "serde_bytes")] &'a [u8],
    u64,
);

/// `server_auth_t1` — the T1 the engine signs in M2. Same function the peer
/// uses to verify; promoted, never reimplemented.
#[allow(dead_code)]
#[allow(clippy::too_many_arguments)]
pub(crate) fn server_auth_t1(
    c1_wire: &[u8],
    engine_ephemeral: [u8; 32],
    engine_static: [u8; 32],
    machine_certificate_digest: [u8; 32],
    engine_key_id: &str,
    channel_id: &[u8],
    channel_epoch: u64,
    challenge_id: &[u8],
    challenge_secret: &[u8],
    authz_epoch: u64,
    roster_digest: &[u8],
    fresh_until: u64,
) -> Result<[u8; 32], OwnerSiteAuthorityError> {
    hash_canonical(&ServerAuthTranscript(
        A2_DOMAIN,
        "server-auth",
        c1_wire,
        &engine_ephemeral,
        &engine_static,
        &machine_certificate_digest,
        engine_key_id,
        channel_id,
        channel_epoch,
        challenge_id,
        challenge_secret,
        authz_epoch,
        roster_digest,
        fresh_until,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn protocol_constants_match_the_pinned_corpus() {
        assert_eq!(
            A2_NOISE_PROTOCOL_NAME,
            "Noise_XXa2v1_25519_ChaChaPoly_SHA256"
        );
        assert_eq!(A2_VERSION, 1);
    }

    #[test]
    fn fresh_static_keypairs_differ() {
        let (a_priv, a_pub) = new_noise_static_keypair().unwrap();
        let (b_priv, b_pub) = new_noise_static_keypair().unwrap();
        assert_ne!(a_pub, b_pub);
        assert_ne!(*a_priv, *b_priv);
    }

    #[test]
    fn server_auth_t1_is_deterministic_and_field_sensitive() {
        let base = server_auth_t1(
            b"c1", [1; 32], [2; 32], [3; 32], "engine", b"ch", 1, b"ci", b"cs", 1, b"rd", 1060,
        )
        .unwrap();
        let again = server_auth_t1(
            b"c1", [1; 32], [2; 32], [3; 32], "engine", b"ch", 1, b"ci", b"cs", 1, b"rd", 1060,
        )
        .unwrap();
        assert_eq!(base, again);
        let other = server_auth_t1(
            b"c1", [9; 32], [2; 32], [3; 32], "engine", b"ch", 1, b"ci", b"cs", 1, b"rd", 1060,
        )
        .unwrap();
        assert_ne!(base, other);
    }
}

#[derive(serde::Serialize)]
struct ChannelBindingTranscript<'a>(
    &'a str,
    &'a str,
    u8,
    &'a str,
    &'a str,
    #[serde(with = "serde_bytes")] &'a [u8],
    #[serde(with = "serde_bytes")] &'a [u8],
    u64,
);

const A2_CHANNEL_BINDING_LABEL: &str = "channel-binding";

/// The final handshake hash — only after the handshake is finished.
#[allow(dead_code)]
pub(crate) fn final_handshake_hash(
    handshake: &HandshakeState,
) -> Result<[u8; 32], OwnerSiteAuthorityError> {
    if !handshake.is_handshake_finished() {
        return Err(OwnerSiteAuthorityError::CborEncode);
    }
    array_32(handshake.get_handshake_hash())
}

/// `channel_binding(h_final, channel_id, channel_epoch)` — same function the
/// peer uses; promoted, never reimplemented.
#[allow(dead_code)]
pub(crate) fn channel_binding(
    h_final: [u8; 32],
    channel_id: &[u8],
    channel_epoch: u64,
) -> Result<[u8; 32], OwnerSiteAuthorityError> {
    if channel_id.len() != 32 || channel_epoch == 0 {
        return Err(OwnerSiteAuthorityError::CborEncode);
    }
    hash_canonical(&ChannelBindingTranscript(
        A2_DOMAIN,
        A2_CHANNEL_BINDING_LABEL,
        A2_VERSION,
        A2_RECORD_PROFILE,
        A2_NOISE_PROTOCOL_NAME,
        &h_final,
        channel_id,
        channel_epoch,
    ))
}

/// A fresh initiator handshake + its static public half. Needed by the peer
/// side in tests and by any future device-side engine code.
#[allow(dead_code)]
pub(crate) fn new_noise_initiator()
-> Result<(HandshakeState, [u8; NOISE_PUBLIC_KEY_BYTES]), OwnerSiteAuthorityError> {
    let prologue = a2_noise_prologue()?;
    let builder = a2_noise_builder(&prologue)?;
    let mut keypair = builder
        .generate_keypair()
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)?;
    let public = array_32(&keypair.public)?;
    let handshake = builder
        .local_private_key(&keypair.private)
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)?
        .build_initiator()
        .map_err(|_| OwnerSiteAuthorityError::CborEncode)?;
    keypair.private.zeroize();
    Ok((handshake, public))
}
