//! S0 — neutral tunnel wire mechanics.
//!
//! Bytes on the wire and the shape of a frame. **No authority lives here**: no
//! admission, no audience, no resource, no identity. Per the approved S0 design
//! the governing test is not "does the name contain claw" — that is a
//! convention, not a mechanism — but whether the item decides *who may do what*.
//!
//! What this module owns: the frame-kind opcodes, [`TunnelFrame`] and its
//! encode/decode, the length cap, the redacted `Debug` impls, the typed
//! [`TargetExit`], the [`MeshIpv4`] wire shape with its route-scope rule, and
//! the *framing* of the 0x17 body as a sealed [`NetworkSettingsBody`].
//!
//! What deliberately stays product-side, and why:
//!
//! - **`HEALTH_PROBE`** — a wire constant whose *value* (`claw-share/health/v1`)
//!   carries the claw namespace. Exporting it from here would let a second
//!   product reuse it and make the two products' probes indistinguishable on the
//!   wire. This module defines the probe's *shape* (a `Health` frame with an
//!   opaque body); each product supplies its own domain-separated value.
//! - **`TunnelAck`** — its `Ok` arm carries `mesh_ipv6` and a `session_id` that
//!   is "stable per credential/slot", i.e. the outputs of claw's identity
//!   derivations. A neutral type with a field only an authority can legitimately
//!   fill is not neutral, so the ack stays where its authority is.
//! - **`NetworkSettings` and the strict `0x17` mirrors** — for exactly the same
//!   reason as the ack: the struct carries the `session_id` the serve loop
//!   stamps. This module frames that body and seals it; only the owning product
//!   can construct or interpret one, and only through its strict decoder.
//! - **The authorization error variants** — `AuthTimeout`, `Rejected`,
//!   `TokenRejected`, `HealthMismatch`. The mechanic/authority line runs *inside*
//!   the old error enum, not around it, so this module carries only
//!   [`WireError`] and each product wraps it.
//! - **The serve loop's `session_id` stamping**, which binds claw session
//!   identity to the settings frame.
//!
//! Behaviour is byte-identical to the pre-extraction claw codec. That is not an
//! assertion here: it is measured by the frozen vectors in
//! `tests/data/s0_claw_wire_vectors_v1.json`, which landed in an **earlier**
//! commit so they cannot have been regenerated by the commit that moved this
//! code.

use std::fmt;

use serde::{Deserialize, Serialize};

/// Frame size cap. Health probes are tiny; this guards against a peer
/// announcing an absurd length and forcing a huge allocation.
pub const MAX_FRAME_LEN: usize = 64 * 1024;

/// Transport-level failures of the wire itself.
///
/// **Closed and non-generic on purpose.** Every variant describes framing or
/// I/O; none describes an authorization outcome. A neutral error carrying
/// `AuthTimeout` or `TokenRejected` would bake a product's authorization model
/// into shared mechanics, and an open payload position (a type parameter, a
/// trait object, a `Custom(T)` arm) would hand the choice of type back to the
/// caller. Products declare their own closed error and wrap this one:
///
/// ```text
/// enum ProductError { Transport(WireError), /* product's own arms */ }
/// impl From<WireError> for ProductError { .. }
/// ```
#[derive(Debug, thiserror::Error, PartialEq, Eq, Clone)]
pub enum WireError {
    #[error("io error: {0}")]
    Io(String),
    #[error("frame too large: {0} bytes")]
    FrameTooLarge(usize),
    #[error("connection closed during {0}")]
    Closed(&'static str),
    #[error("cbor: {0}")]
    Cbor(String),
    #[error("server returned an unexpected ack")]
    UnexpectedAck,
    #[error("invalid frame: {0}")]
    InvalidFrame(String),
    #[error("target service unavailable: {0}")]
    TargetUnavailable(String),
}

// ─── Interface parameters carried by the 0x17 frame ─────────────────────────

/// The guest's tunnel IPv4 interface parameters for the `IpTunnel` path.
///
/// ROUTE-SCOPE INVARIANT (contract, enforced server-side and by the client FFI):
/// the ONLY route the client installs is the pool CIDR `network(addr,
/// prefix_len)` — NEVER a default route (`0.0.0.0/0`). A real default route /
/// exit-node is a separate authenticated policy decision, never inferred from
/// these settings. `peer` is a DISTINCT unicast host inside that same prefix.
///
/// See [`MeshIpv4::route_scope_violation`] — the rule travels with the type as a
/// callable check, not as a comment a future consumer may not read.
#[derive(Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct MeshIpv4 {
    /// The guest's assigned tunnel address, e.g. "10.42.0.2".
    pub addr: String,
    /// CIDR prefix length; the client derives the subnet mask and installs a
    /// route for exactly `network(addr, prefix_len)`, never `0.0.0.0/0`.
    pub prefix_len: u8,
    /// The peer / tunnel-remote address, e.g. "10.42.0.3" — a distinct
    /// unicast host inside the same prefix.
    pub peer: String,
}

/// Why a set of interface parameters must not be installed as a route.
///
/// Fieldless: a rejection reason is not a place to smuggle caller-chosen data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum RouteScopeViolation {
    /// `prefix_len == 0` is `0.0.0.0/0` — a default route by another name.
    #[error("prefix_len 0 is a default route")]
    DefaultRoute,
    /// `prefix_len` exceeds the width of an IPv4 address.
    #[error("prefix_len exceeds 32")]
    PrefixTooLong,
    /// The address is not parseable as IPv4.
    #[error("addr is not a valid IPv4 address")]
    AddrNotIpv4,
    /// The peer is not parseable as IPv4.
    #[error("peer is not a valid IPv4 address")]
    PeerNotIpv4,
    /// `peer` must be a *distinct* host; equal addresses are not a point-to-point
    /// pair.
    #[error("peer equals addr")]
    PeerEqualsAddr,
    /// `peer` must sit inside the same prefix as `addr`; otherwise installing the
    /// prefix route does not actually reach it.
    #[error("peer is outside addr's prefix")]
    PeerOutsidePrefix,
}

impl MeshIpv4 {
    /// The route-scope rule, as a mechanism.
    ///
    /// Returns `Some(..)` when these parameters must **not** be turned into a
    /// route. The design is explicit that extracting the wire type without the
    /// rule would leave a neutral decoder happily yielding settings a consumer
    /// could install as a default route.
    ///
    /// Deliberately **not** wired into [`TunnelFrame::decode`]: doing so would
    /// change claw's decode behaviour for inputs it currently accepts, and this
    /// slice is required to be byte-identical. Consumers call it before
    /// configuring an interface.
    #[must_use]
    pub fn route_scope_violation(&self) -> Option<RouteScopeViolation> {
        if self.prefix_len == 0 {
            return Some(RouteScopeViolation::DefaultRoute);
        }
        if self.prefix_len > 32 {
            return Some(RouteScopeViolation::PrefixTooLong);
        }
        let Ok(addr) = self.addr.parse::<std::net::Ipv4Addr>() else {
            return Some(RouteScopeViolation::AddrNotIpv4);
        };
        let Ok(peer) = self.peer.parse::<std::net::Ipv4Addr>() else {
            return Some(RouteScopeViolation::PeerNotIpv4);
        };
        if addr == peer {
            return Some(RouteScopeViolation::PeerEqualsAddr);
        }
        let shift = 32 - u32::from(self.prefix_len);
        let mask = if shift == 32 { 0 } else { u32::MAX << shift };
        if (u32::from(addr) & mask) != (u32::from(peer) & mask) {
            return Some(RouteScopeViolation::PeerOutsidePrefix);
        }
        None
    }
}

impl fmt::Debug for MeshIpv4 {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Addresses reveal VPN topology; redact like the ack's mesh field.
        f.debug_struct("MeshIpv4")
            .field("addr", &"<redacted>")
            .field("prefix_len", &self.prefix_len)
            .field("peer", &"<redacted>")
            .finish()
    }
}

// The settings STRUCT is deliberately NOT here. It carries a `session_id` that
// the serve loop stamps to match the auth ack — the design classifies that
// stamping as authority, and its refined rule is that a neutral type may not
// carry a field whose only legitimate producer is an authority. That rule is
// what expelled `TunnelAck`; `NetworkSettings` carries the same field for the
// same reason, and the measurement confirms it is used as identity rather than
// transport (`claw-share-bridge-rs` compares `ns.session_id != expected`).
//
// So this module owns the 0x17 *frame* — opcode, envelope, framing — and the
// body travels as opaque bytes. The product that owns the identity owns the
// struct, the strict wire mirrors, and the canonical decode. Wire bytes are
// unchanged: the body is the same canonical CBOR either way, which is exactly
// what the frozen vectors keep proving.
//
// `MeshIpv4` above stays neutral: `addr` / `prefix_len` / `peer` are topology,
// not identity, and the design already blessed the server-allocated pool address
// when it classified `TargetSession::vpn_mesh_ipv4` as mechanic.

/// The 0x17 body, opaque and **sealed**.
///
/// Bytes this module frames and never interprets. The field is private and there
/// is no public accessor or constructor: the only public doors are
/// `claw_share_data_tunnel::{encode,decode}_network_settings_body`, and the
/// decode one applies the strict canonical mirrors.
///
/// **Why sealed rather than a bare `Vec<u8>`.** A plain public body would have
/// let any consumer read or fabricate settings bytes without the strict check,
/// and the pre-extraction code deliberately made that impossible — its own words
/// were that the strictness "cannot escape `TunnelFrame::decode`". Measured
/// while implementing: with a bare `Vec<u8>`, `TunnelFrame::decode` accepted
/// non-canonical key order, unknown keys and trailing bytes, and the three
/// external consumers (`claw-share-bridge-rs` ×2, `t1-iptunnel-dev-runner-rs`)
/// would each have had to remember to validate. This frame configures a VPN
/// interface before any packet pump, so that fail-closed property is the one
/// that matters. Sealing restores it: outside this crate the bytes are
/// unreachable except through the product's strict decoder.
///
/// So the module holds no identity (it cannot even see the `session_id` inside),
/// and strictness still cannot escape. Wire bytes are unchanged either way.
#[derive(Clone, PartialEq, Eq)]
pub struct NetworkSettingsBody(Vec<u8>);

impl NetworkSettingsBody {
    /// Crate-internal only: the framing layer needs the bytes to write them.
    pub(crate) fn as_bytes(&self) -> &[u8] {
        &self.0
    }

    /// Crate-internal only: the framing layer produces this on decode, and the
    /// product's encoder produces it from an already-canonical encoding.
    pub(crate) fn from_bytes(bytes: Vec<u8>) -> Self {
        Self(bytes)
    }

    /// Length is not sensitive and is useful for diagnostics; the content is.
    #[must_use]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl fmt::Debug for NetworkSettingsBody {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("NetworkSettingsBody")
            .field("len", &self.0.len())
            .field("bytes", &"<redacted>")
            .finish()
    }
}

// ─── Typed data frames (post-auth) ──────────────────────────────────────────

/// Frame kind byte prefixed to every post-auth payload.
///
/// `Health` is a liveness probe (echoed → tunnel ready). The rest drive a
/// PERSISTENT bidirectional stream to the target: the engine holds one target
/// connection per session and pipes `Data` both ways until `Close`/`Error`/EOF.
/// `Window` carries a backpressure credit. `Resize` carries terminal
/// dimensions; `Exit` carries the target process's typed exit status.
pub const FRAME_HEALTH: u8 = 0x01;
pub const FRAME_OPEN: u8 = 0x10;
pub const FRAME_DATA: u8 = 0x11;
pub const FRAME_CLOSE: u8 = 0x12;
pub const FRAME_ERROR: u8 = 0x13;
pub const FRAME_WINDOW: u8 = 0x14;
pub const FRAME_RESIZE: u8 = 0x15;
pub const FRAME_EXIT: u8 = 0x16;
/// `IpTunnel`-only: post-Open server→client interface settings.
/// Body is canonical CBOR of [`NetworkSettings`].
pub const FRAME_NETWORK_SETTINGS: u8 = 0x17;

/// Typed exit status of an interactive target process.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetExit {
    /// Normal exit with this status code.
    Code(i32),
    /// Terminated by this signal number.
    Signal(i32),
    /// The target ended without a recoverable status (killed/dropped).
    Lost,
}

impl TargetExit {
    const TAG_CODE: u8 = 0x01;
    const TAG_SIGNAL: u8 = 0x02;
    const TAG_LOST: u8 = 0x03;

    fn encode(self) -> [u8; 5] {
        let (tag, val): (u8, i32) = match self {
            Self::Code(c) => (Self::TAG_CODE, c),
            Self::Signal(s) => (Self::TAG_SIGNAL, s),
            Self::Lost => (Self::TAG_LOST, 0),
        };
        let v = val.to_be_bytes();
        [tag, v[0], v[1], v[2], v[3]]
    }

    fn decode(payload: &[u8]) -> Result<Self, WireError> {
        let arr: [u8; 5] = payload
            .try_into()
            .map_err(|_| WireError::InvalidFrame("bad exit frame".into()))?;
        let val = i32::from_be_bytes([arr[1], arr[2], arr[3], arr[4]]);
        match arr[0] {
            Self::TAG_CODE => Ok(Self::Code(val)),
            Self::TAG_SIGNAL => Ok(Self::Signal(val)),
            Self::TAG_LOST => Ok(Self::Lost),
            other => Err(WireError::InvalidFrame(format!(
                "unknown exit tag {other:#04x}"
            ))),
        }
    }
}

#[derive(Clone, PartialEq, Eq)]
pub enum TunnelFrame {
    /// Liveness probe / echo. The body is opaque here on purpose: each product
    /// supplies its own domain-separated probe value.
    Health(Vec<u8>),
    /// Open the persistent stream to the session's target.
    Open,
    /// Bidirectional stream bytes.
    Data(Vec<u8>),
    /// Clean close of the stream (either direction).
    Close,
    /// Typed error; payload is a stable reason string.
    Error(String),
    /// Backpressure credit: the peer may send up to `n` more bytes.
    Window(u32),
    /// Terminal resize (client → engine): the target PTY's column/row count.
    Resize { cols: u16, rows: u16 },
    /// Target process exit (engine → client): the typed exit status, sent
    /// just before the closing [`TunnelFrame::Close`].
    Exit(TargetExit),
    /// `IpTunnel`-only (engine → client): the interface settings, sent
    /// immediately after the Open-ack.
    ///
    /// The body is **opaque and sealed here**: canonical CBOR whose shape
    /// belongs to the product, because it carries a `session_id` that only an
    /// authority may produce. This module frames it and cannot interpret it, and
    /// no consumer can read or fabricate it except through the product's strict
    /// decoder — see [`NetworkSettingsBody`] and `claw_share_data_tunnel`.
    NetworkSettings(NetworkSettingsBody),
}

struct RedactedFramePayload {
    len: usize,
}

impl fmt::Debug for RedactedFramePayload {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Payload")
            .field("len", &self.len)
            .field("bytes", &"<redacted>")
            .finish()
    }
}

struct RedactedFrameText {
    len: usize,
}

impl fmt::Debug for RedactedFrameText {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Text")
            .field("len", &self.len)
            .field("value", &"<redacted>")
            .finish()
    }
}

impl fmt::Debug for TunnelFrame {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Health(payload) => f
                .debug_tuple("Health")
                .field(&RedactedFramePayload { len: payload.len() })
                .finish(),
            Self::Open => f.write_str("Open"),
            Self::Data(payload) => f
                .debug_tuple("Data")
                .field(&RedactedFramePayload { len: payload.len() })
                .finish(),
            Self::Close => f.write_str("Close"),
            Self::Error(reason) => f
                .debug_tuple("Error")
                .field(&RedactedFrameText { len: reason.len() })
                .finish(),
            Self::Window(n) => f.debug_tuple("Window").field(n).finish(),
            Self::Resize { cols, rows } => f
                .debug_struct("Resize")
                .field("cols", cols)
                .field("rows", rows)
                .finish(),
            Self::Exit(status) => f.debug_tuple("Exit").field(status).finish(),
            // The body is opaque AND carries an identity field, so it is
            // redacted like every other payload rather than printed.
            Self::NetworkSettings(body) => f.debug_tuple("NetworkSettings").field(body).finish(),
        }
    }
}

impl TunnelFrame {
    #[must_use]
    pub fn encode(&self) -> Vec<u8> {
        let mut out = Vec::new();
        match self {
            Self::Health(p) => {
                out.push(FRAME_HEALTH);
                out.extend_from_slice(p);
            }
            Self::Open => out.push(FRAME_OPEN),
            Self::Data(p) => {
                out.push(FRAME_DATA);
                out.extend_from_slice(p);
            }
            Self::Close => out.push(FRAME_CLOSE),
            Self::Error(reason) => {
                out.push(FRAME_ERROR);
                out.extend_from_slice(reason.as_bytes());
            }
            Self::Window(n) => {
                out.push(FRAME_WINDOW);
                out.extend_from_slice(&n.to_be_bytes());
            }
            Self::Resize { cols, rows } => {
                out.push(FRAME_RESIZE);
                out.extend_from_slice(&cols.to_be_bytes());
                out.extend_from_slice(&rows.to_be_bytes());
            }
            Self::Exit(status) => {
                out.push(FRAME_EXIT);
                out.extend_from_slice(&status.encode());
            }
            Self::NetworkSettings(body) => {
                out.push(FRAME_NETWORK_SETTINGS);
                // The body arrives already canonical from the owning product;
                // framing it verbatim is what keeps the wire bytes identical to
                // the pre-extraction encoder. `as_bytes` is pub(crate): the
                // framing layer may see the bytes, no external consumer may.
                out.extend_from_slice(body.as_bytes());
            }
        }
        out
    }

    pub fn decode(bytes: &[u8]) -> Result<Self, WireError> {
        let (&kind, payload) = bytes
            .split_first()
            .ok_or_else(|| WireError::InvalidFrame("empty frame".into()))?;
        match kind {
            FRAME_HEALTH => Ok(Self::Health(payload.to_vec())),
            FRAME_OPEN => Ok(Self::Open),
            FRAME_DATA => Ok(Self::Data(payload.to_vec())),
            FRAME_CLOSE => Ok(Self::Close),
            FRAME_ERROR => Ok(Self::Error(String::from_utf8_lossy(payload).into_owned())),
            FRAME_WINDOW => {
                let arr: [u8; 4] = payload
                    .try_into()
                    .map_err(|_| WireError::InvalidFrame("bad window frame".into()))?;
                Ok(Self::Window(u32::from_be_bytes(arr)))
            }
            FRAME_RESIZE => {
                let arr: [u8; 4] = payload
                    .try_into()
                    .map_err(|_| WireError::InvalidFrame("bad resize frame".into()))?;
                Ok(Self::Resize {
                    cols: u16::from_be_bytes([arr[0], arr[1]]),
                    rows: u16::from_be_bytes([arr[2], arr[3]]),
                })
            }
            FRAME_EXIT => Ok(Self::Exit(TargetExit::decode(payload)?)),
            // The body is handed back unparsed. The strictness this frame needs
            // — exact canonical encoding, no unmodelled key, no trailing bytes,
            // fail closed before any interface exists — is not weakened, it is
            // applied by the product that owns the struct, because that struct
            // carries an identity field this module must not hold.
            FRAME_NETWORK_SETTINGS => Ok(Self::NetworkSettings(NetworkSettingsBody::from_bytes(
                payload.to_vec(),
            ))),
            other => Err(WireError::InvalidFrame(format!(
                "unknown frame kind {other:#04x}"
            ))),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The route-scope rule is a mechanism here, not a comment — so it is
    /// exercised in both directions, with a positive control so the negatives
    /// cannot pass by rejecting everything.
    #[test]
    fn route_scope_rule_rejects_a_default_route_and_accepts_a_real_prefix() {
        // Positive control first: a legitimate pool CIDR passes.
        let ok = MeshIpv4 {
            addr: "10.42.0.2".into(),
            prefix_len: 24,
            peer: "10.42.0.1".into(),
        };
        assert_eq!(ok.route_scope_violation(), None);

        // prefix_len 0 IS 0.0.0.0/0 — the prohibition the design names.
        let default_route = MeshIpv4 {
            prefix_len: 0,
            ..ok.clone()
        };
        assert_eq!(
            default_route.route_scope_violation(),
            Some(RouteScopeViolation::DefaultRoute)
        );

        for (case, m) in [
            (
                RouteScopeViolation::PrefixTooLong,
                MeshIpv4 {
                    prefix_len: 33,
                    ..ok.clone()
                },
            ),
            (
                RouteScopeViolation::AddrNotIpv4,
                MeshIpv4 {
                    addr: "not-an-ip".into(),
                    ..ok.clone()
                },
            ),
            (
                RouteScopeViolation::PeerNotIpv4,
                MeshIpv4 {
                    peer: "::1".into(),
                    ..ok.clone()
                },
            ),
            (
                RouteScopeViolation::PeerEqualsAddr,
                MeshIpv4 {
                    peer: ok.addr.clone(),
                    ..ok.clone()
                },
            ),
            (
                RouteScopeViolation::PeerOutsidePrefix,
                MeshIpv4 {
                    peer: "10.99.0.1".into(),
                    ..ok.clone()
                },
            ),
        ] {
            assert_eq!(m.route_scope_violation(), Some(case), "{case:?}");
        }
    }

    /// Guard layer 4 (domain separation) — **PARTIAL / FIXTURE-ONLY, NOT CLOSED.**
    ///
    /// What this test actually establishes: two hardcoded payloads encode
    /// differently, and no namespaced probe value lives in the neutral module's
    /// production projection. That is all.
    ///
    /// What the design's layer-4 bar requires and this does **not** yet do:
    /// an enumerated set of the shared wire constants *and* shared wire
    /// types/encodings; a mandatory per-product domain tag or prefix in the
    /// encoding; pairwise-distinctness across that whole set; mutants for
    /// collision, for a missing tag and for the *other* product's tag; and the
    /// requirement that bytes produced by one product are rejected by the other
    /// product's decoder.
    ///
    /// It is recorded as partial in the code, not only in review, because a
    /// half-built guard that reads as finished is the failure this slice keeps
    /// finding. It joins layers 2 and 3 as fixture-only: there is still no
    /// second product to enumerate against — `DeviceMeshOffer` exists in zero
    /// files — so the missing half has no live subject either.
    #[test]
    fn health_frame_body_is_opaque_and_carries_no_product_value() {
        let a = TunnelFrame::Health(b"product-a/health/v1".to_vec());
        let b = TunnelFrame::Health(b"product-b/health/v1".to_vec());
        assert_ne!(
            a.encode(),
            b.encode(),
            "two products' probes must be distinguishable on the wire"
        );
        // ...and this module defines no probe value of its own.
        //
        // Scoped to the PRODUCTION half. The first version of this check scanned
        // the whole file and failed against its own assertion text — the needle
        // string lives in the test that searches for it, so the probe counted
        // itself. Cutting at the test module is the same projection the R0a
        // scope guard uses, and it is what makes the result about production.
        // Comment lines are stripped as well as the test module: this module's
        // own docs explain the rule by NAMING the excluded value, and a scan
        // that could not tell an explanation from a definition would report the
        // documentation as the violation.
        let src = include_str!("tunnel_wire.rs");
        let head = src
            .split_once("\n#[cfg(test)]\n")
            .map_or(src, |(head, _)| head);
        let production: String = head
            .lines()
            .filter(|l| !l.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            production.contains("pub enum TunnelFrame"),
            "positive control: the production projection must be non-empty and \
             must be the region the ban below is meant to cover"
        );
        for banned in ["claw-share/health", "const HEALTH_PROBE"] {
            assert!(
                !production.contains(banned),
                "a namespaced probe value must not live in the neutral module: {banned}"
            );
        }
    }

    /// Redaction travels with the codec: a neutral module that prints payloads
    /// is a new leak, not a neutral move.
    #[test]
    fn debug_redacts_payloads_reasons_and_addresses() {
        let d = format!("{:?}", TunnelFrame::Data(b"secret-bytes".to_vec()));
        assert!(
            d.contains("<redacted>") && !d.contains("secret-bytes"),
            "{d}"
        );

        let e = format!("{:?}", TunnelFrame::Error("secret-reason".into()));
        assert!(
            e.contains("<redacted>") && !e.contains("secret-reason"),
            "{e}"
        );

        // The 0x17 body is opaque here, so redaction is about the bytes: a body
        // that happens to contain an address or a session id must not surface
        // through Debug just because this module does not parse it.
        let body = b"\x69mesh_ipv4\x6910.42.0.2s_secret".to_vec();
        let sealed = NetworkSettingsBody::from_bytes(body.clone());
        let ns = format!("{:?}", TunnelFrame::NetworkSettings(sealed));
        assert!(!ns.contains("10.42.0.2"), "{ns}");
        assert!(!ns.contains("s_secret"), "{ns}");
        assert!(
            ns.contains(&body.len().to_string()),
            "the length is not sensitive and stays visible, so the redaction is \
             not simply printing nothing: {ns}"
        );
    }
}
